import type { DefaultTheme } from 'vitepress'

export const sidebar: DefaultTheme.Config['sidebar'] = {

    '/': [
        { text: "学习路径", link: "/guide" },
        {
            text: "LeetCode",
            collapsed: true,
            items: [
                { text: '1. 两数之和', link: '/leetcode/1-two-sum' },
                { text: '2. 两数相加', link: '/leetcode/2-add-two-numbers' },
                { text: '3. 无重复字符的最长子串', link: '/leetcode/3-longest-substring-without-repeating-characters' },
                { text: '4. 寻找两个正序数组的中位数', link: '/leetcode/4-median-of-two-sorted-arrays' },
                { text: '5. 最长回文子串', link: '/leetcode/5-longest-palindromic-substring' },
                { text: '6. Z 字形变换', link: '/leetcode/6-zigzag-conversion' },
                { text: '7. 整数反转', link: '/leetcode/7-reverse-integer' },
                { text: '8. 字符串转换整数 (atoi)', link: '/leetcode/8-string-to-integer-atoi' },
                { text: '9. 回文数', link: '/leetcode/9-palindrome-number' },
                { text: '10. 正则表达式匹配', link: '/leetcode/10-regular-expression-matching' },
                { text: '11. 盛最多水的容器', link: '/leetcode/11-container-with-most-water' },
                { text: '12. 整数转罗马数字', link: '/leetcode/12-integer-to-roman' },
                { text: '13. 罗马数字转整数', link: '/leetcode/13-roman-to-integer' },
                { text: '14. 最长公共前缀', link: '/leetcode/14-longest-common-prefix' },
                { text: '15. 三数之和', link: '/leetcode/15-3sum' },
                { text: '16. 最接近的三数之和', link: '/leetcode/16-3sum-closest' },
                { text: '17. 电话号码的字母组合', link: '/leetcode/17-letter-combinations-of-a-phone-number' },
                { text: '18. 四数之和', link: '/leetcode/18-4sum' },
                { text: '19. 删除链表的倒数第 N 个结点', link: '/leetcode/19-remove-nth-node-from-end-of-list' },
                { text: '20. 有效的括号', link: '/leetcode/20-valid-parentheses' },
                { text: '21. 合并两个有序链表', link: '/leetcode/21-merge-two-sorted-lists' },
                { text: '22. 括号生成', link: '/leetcode/22-generate-parentheses' },
                { text: '23. 合并 K 个升序链表', link: '/leetcode/23-merge-k-sorted-lists' },
                { text: '24. 两两交换链表中的节点', link: '/leetcode/24-swap-nodes-in-pairs' },
                { text: '25. K 个一组翻转链表', link: '/leetcode/25-reverse-nodes-in-k-group' },
                { text: '26. 删除有序数组中的重复项', link: '/leetcode/26-remove-duplicates-from-sorted-array' },
                { text: '27. 移除元素', link: '/leetcode/27-remove-element' },
                { text: '28. 找出字符串中第一个匹配项的下标', link: '/leetcode/28-find-the-index-of-the-first-occurrence-in-a-string' },
                { text: '29. 两数相除', link: '/leetcode/29-divide-two-integers' },
                { text: '30. 串联所有单词的子串', link: '/leetcode/30-substring-with-concatenation-of-all-words' },
                { text: '31. 下一个排列', link: '/leetcode/31-next-permutation' },
                { text: '32. 最长有效括号', link: '/leetcode/32-longest-valid-parentheses' },
                { text: '33. 搜索旋转排序数组', link: '/leetcode/33-search-in-rotated-sorted-array' },
                { text: '34. 在排序数组中查找元素的第一个和最后一个位置', link: '/leetcode/34-find-first-and-last-position-of-element-in-sorted-array' },
                { text: '35. 搜索插入位置', link: '/leetcode/35-search-insert-position' },
                { text: '36. 有效的数独', link: '/leetcode/36-valid-sudoku' },
                { text: '37. 解数独', link: '/leetcode/37-sudoku-solver' },
                { text: '38. 外观数列', link: '/leetcode/38-count-and-say' },
                { text: '39. 组合总和', link: '/leetcode/39-combination-sum' },
                { text: '40. 组合总和 II', link: '/leetcode/40-combination-sum-ii' },
                { text: '41. 缺失的第一个正数', link: '/leetcode/41-first-missing-positive' },
                { text: '42. 接雨水', link: '/leetcode/42-trapping-rain-water' },
                { text: '43. 字符串相乘', link: '/leetcode/43-multiply-strings' },
                { text: '44. 通配符匹配', link: '/leetcode/44-wildcard-matching' },
                { text: '45. 跳跃游戏 II', link: '/leetcode/45-jump-game-ii' },
                { text: '46. 全排列', link: '/leetcode/46-permutations' },
                { text: '47. 全排列 II', link: '/leetcode/47-permutations-ii' },
                { text: '48. 旋转图像', link: '/leetcode/48-rotate-image' },
                { text: '49. 字母异位词分组', link: '/leetcode/49-group-anagrams' },
                { text: '50. Pow(x, n)', link: '/leetcode/50-powx-n' },
                { text: '51. N 皇后', link: '/leetcode/51-n-queens' },
                { text: '52. N 皇后 II', link: '/leetcode/52-n-queens-ii' },
                { text: '53. 最大子数组和', link: '/leetcode/53-maximum-subarray' },
                { text: '54. 螺旋矩阵', link: '/leetcode/54-spiral-matrix' },
                { text: '55. 跳跃游戏', link: '/leetcode/55-jump-game' },
                { text: '56. 合并区间', link: '/leetcode/56-merge-intervals' },
                { text: '57. 插入区间', link: '/leetcode/57-insert-interval' },
                { text: '58. 最后一个单词的长度', link: '/leetcode/58-length-of-last-word' },
                { text: '59. 螺旋矩阵 II', link: '/leetcode/59-spiral-matrix-ii' },
                { text: '60. 排列序列', link: '/leetcode/60-permutation-sequence' },
                { text: '61. 旋转链表', link: '/leetcode/61-rotate-list' },
                { text: '62. 不同路径', link: '/leetcode/62-unique-paths' },
                { text: '63. 不同路径 II', link: '/leetcode/63-unique-paths-ii' },
                { text: '64. 最小路径和', link: '/leetcode/64-minimum-path-sum' },
                { text: '65. 有效数字', link: '/leetcode/65-valid-number' },
                { text: '66. 加一', link: '/leetcode/66-plus-one' },
                { text: '67. 二进制求和', link: '/leetcode/67-add-binary' },
                { text: '68. 文本左右对齐', link: '/leetcode/68-text-justification' },
                { text: '69. x 的平方根', link: '/leetcode/69-sqrtx' },
                { text: '70. 爬楼梯', link: '/leetcode/70-climbing-stairs' },
                { text: '71. 简化路径', link: '/leetcode/71-simplify-path' },
                { text: '72. 编辑距离', link: '/leetcode/72-edit-distance' },
                { text: '73. 矩阵置零', link: '/leetcode/73-set-matrix-zeroes' },
                { text: '74. 搜索二维矩阵', link: '/leetcode/74-search-a-2d-matrix' },
                { text: '75. 颜色分类', link: '/leetcode/75-sort-colors' },
                { text: '76. 最小覆盖子串', link: '/leetcode/76-minimum-window-substring' },
                { text: '77. 组合', link: '/leetcode/77-combinations' },
                { text: '78. 子集', link: '/leetcode/78-subsets' },
                { text: '79. 单词搜索', link: '/leetcode/79-word-search' },
                { text: '80. 删除有序数组中的重复项 II', link: '/leetcode/80-remove-duplicates-from-sorted-array-ii' },
                { text: '81. 搜索旋转排序数组 II', link: '/leetcode/81-search-in-rotated-sorted-array-ii' },
                { text: '82. 删除排序链表中的重复元素 II', link: '/leetcode/82-remove-duplicates-from-sorted-list-ii' },
                { text: '83. 删除排序链表中的重复元素', link: '/leetcode/83-remove-duplicates-from-sorted-list' },
                { text: '84. 柱状图中最大的矩形', link: '/leetcode/84-largest-rectangle-in-histogram' },
                { text: '85. 最大矩形', link: '/leetcode/85-maximal-rectangle' },
                { text: '86. 分隔链表', link: '/leetcode/86-partition-list' },
                { text: '87. 扰乱字符串', link: '/leetcode/87-scramble-string' },
                { text: '88. 合并两个有序数组', link: '/leetcode/88-merge-sorted-array' },
                { text: '89. 格雷编码', link: '/leetcode/89-gray-code' },
                { text: '90. 子集 II', link: '/leetcode/90-subsets-ii' },
                { text: '91. 解码方法', link: '/leetcode/91-decode-ways' },
                { text: '92. 反转链表 II', link: '/leetcode/92-reverse-linked-list-ii' },
                { text: '93. 复原 IP 地址', link: '/leetcode/93-restore-ip-addresses' },
                { text: '94. 二叉树的中序遍历', link: '/leetcode/94-binary-tree-inorder-traversal' },
                { text: '95. 不同的二叉搜索树 II', link: '/leetcode/95-unique-binary-search-trees-ii' },
                { text: '96. 不同的二叉搜索树', link: '/leetcode/96-unique-binary-search-trees' },
                { text: '97. 交错字符串', link: '/leetcode/97-interleaving-string' },
                { text: '98. 验证二叉搜索树', link: '/leetcode/98-validate-binary-search-tree' },
                { text: '99. 恢复二叉搜索树', link: '/leetcode/99-recover-binary-search-tree' },
                { text: '100. 相同的树', link: '/leetcode/100-same-tree' },
                { text: '101. 对称二叉树', link: '/leetcode/101-symmetric-tree' },
                { text: '102. 二叉树的层序遍历', link: '/leetcode/102-binary-tree-level-order-traversal' },
                { text: '103. 二叉树的锯齿形层序遍历', link: '/leetcode/103-binary-tree-zigzag-level-order-traversal' },
                { text: '104. 二叉树的最大深度', link: '/leetcode/104-maximum-depth-of-binary-tree' },
                { text: '105. 从前序与中序遍历序列构造二叉树', link: '/leetcode/105-construct-binary-tree-from-preorder-and-inorder-traversal' },
                { text: '106. 从中序与后序遍历序列构造二叉树', link: '/leetcode/106-construct-binary-tree-from-inorder-and-postorder-traversal' },
                { text: '107. 二叉树的层序遍历 II', link: '/leetcode/107-binary-tree-level-order-traversal-ii' },
                { text: '108. 将有序数组转换为二叉搜索树', link: '/leetcode/108-convert-sorted-array-to-binary-search-tree' },
                { text: '109. 有序链表转换二叉搜索树', link: '/leetcode/109-convert-sorted-list-to-binary-search-tree' },
                { text: '110. 平衡二叉树', link: '/leetcode/110-balanced-binary-tree' },
                { text: '111. 二叉树的最小深度', link: '/leetcode/111-minimum-depth-of-binary-tree' },
                { text: '112. 路径总和', link: '/leetcode/112-path-sum' },
                { text: '113. 路径总和 II', link: '/leetcode/113-path-sum-ii' },
                { text: '114. 二叉树展开为链表', link: '/leetcode/114-flatten-binary-tree-to-linked-list' },
                { text: '115. 不同的子序列', link: '/leetcode/115-distinct-subsequences' },
                { text: '116. 填充每个节点的下一个右侧节点指针', link: '/leetcode/116-populating-next-right-pointers-in-each-node' },
                { text: '117. 填充每个节点的下一个右侧节点指针 II', link: '/leetcode/117-populating-next-right-pointers-in-each-node-ii' },
                { text: '118. 杨辉三角', link: '/leetcode/118-pascals-triangle' },
                { text: '119. 杨辉三角 II', link: '/leetcode/119-pascals-triangle-ii' },
                { text: '120. 三角形最小路径和', link: '/leetcode/120-triangle' },
                { text: '121. 买卖股票的最佳时机', link: '/leetcode/121-best-time-to-buy-and-sell-stock' },
                { text: '122. 买卖股票的最佳时机 II', link: '/leetcode/122-best-time-to-buy-and-sell-stock-ii' },
                { text: '123. 买卖股票的最佳时机 III', link: '/leetcode/123-best-time-to-buy-and-sell-stock-iii' },
                { text: '124. 二叉树中的最大路径和', link: '/leetcode/124-binary-tree-maximum-path-sum' },
                { text: '125. 验证回文串', link: '/leetcode/125-valid-palindrome' },
                { text: '126. 单词接龙 II', link: '/leetcode/126-word-ladder-ii' },
                { text: '127. 单词接龙', link: '/leetcode/127-word-ladder' },
                { text: '128. 最长连续序列', link: '/leetcode/128-longest-consecutive-sequence' },
                { text: '129. 求根节点到叶节点数字之和', link: '/leetcode/129-sum-root-to-leaf-numbers' },
                { text: '130. 被围绕的区域', link: '/leetcode/130-surrounded-regions' },
                { text: '131. 分割回文串', link: '/leetcode/131-palindrome-partitioning' },
                { text: '132. 分割回文串 II', link: '/leetcode/132-palindrome-partitioning-ii' },
                { text: '133. 克隆图', link: '/leetcode/133-clone-graph' },
                { text: '134. 加油站', link: '/leetcode/134-gas-station' },
                { text: '135. 分发糖果', link: '/leetcode/135-candy' },
                { text: '136. 只出现一次的数字', link: '/leetcode/136-single-number' },
                { text: '137. 只出现一次的数字 II', link: '/leetcode/137-single-number-ii' },
                { text: '138. 随机链表的复制', link: '/leetcode/138-copy-list-with-random-pointer' },
                { text: '139. 单词拆分', link: '/leetcode/139-word-break' },
                { text: '140. 单词拆分 II', link: '/leetcode/140-word-break-ii' },
                { text: '141. 环形链表', link: '/leetcode/141-linked-list-cycle' },
                { text: '142. 环形链表 II', link: '/leetcode/142-linked-list-cycle-ii' },
                { text: '143. 重排链表', link: '/leetcode/143-reorder-list' },
                { text: '144. 二叉树的前序遍历', link: '/leetcode/144-binary-tree-preorder-traversal' },
                { text: '145. 二叉树的后序遍历', link: '/leetcode/145-binary-tree-postorder-traversal' },
                { text: '146. LRU 缓存', link: '/leetcode/146-lru-cache' },
                { text: '147. 对链表进行插入排序', link: '/leetcode/147-insertion-sort-list' },
                { text: '148. 排序链表', link: '/leetcode/148-sort-list' },
                { text: '149. 直线上最多的点数', link: '/leetcode/149-max-points-on-a-line' },
                { text: '150. 逆波兰表达式求值', link: '/leetcode/150-evaluate-reverse-polish-notation' },
                { text: '151. 反转字符串中的单词', link: '/leetcode/151-reverse-words-in-a-string' },
                { text: '152. 乘积最大子数组', link: '/leetcode/152-maximum-product-subarray' },
                { text: '153. 寻找旋转排序数组中的最小值', link: '/leetcode/153-find-minimum-in-rotated-sorted-array' },
                { text: '154. 寻找旋转排序数组中的最小值 II', link: '/leetcode/154-find-minimum-in-rotated-sorted-array-ii' },
                { text: '155. 最小栈', link: '/leetcode/155-min-stack' },
                { text: '156. 上下翻转二叉树', link: '/leetcode/156-binary-tree-upside-down' },
                { text: '157. 用 Read4 读取 N 个字符', link: '/leetcode/157-read-n-characters-given-read4' },
                { text: '158. 用 Read4 读取 N 个字符 II', link: '/leetcode/158-read-n-characters-given-read4-ii' },
                { text: '159. 至多包含两个不同字符的最长子串', link: '/leetcode/159-longest-substring-with-at-most-two-distinct-characters' },
                { text: '160. 相交链表', link: '/leetcode/160-intersection-of-two-linked-lists' },
                { text: '161. 相隔为 1 的编辑距离', link: '/leetcode/161-one-edit-distance' },
                { text: '162. 寻找峰值', link: '/leetcode/162-find-peak-element' },
                { text: '163. 缺失的区间', link: '/leetcode/163-missing-ranges' },
                { text: '164. 最大间距', link: '/leetcode/164-maximum-gap' },
                { text: '165. 比较版本号', link: '/leetcode/165-compare-version-numbers' },
                { text: '166. 分数到小数', link: '/leetcode/166-fraction-to-recurring-decimal' },
                { text: '167. 两数之和 II - 输入有序数组', link: '/leetcode/167-two-sum-ii-input-array-is-sorted' },
                { text: '168. Excel 表列名称', link: '/leetcode/168-excel-sheet-column-title' },
                { text: '169. 多数元素', link: '/leetcode/169-majority-element' },
                { text: '170. 两数之和 III - 数据结构设计', link: '/leetcode/170-two-sum-iii-data-structure-design' },
                { text: '171. Excel 表列序号', link: '/leetcode/171-excel-sheet-column-number' },
                { text: '172. 阶乘后的零', link: '/leetcode/172-factorial-trailing-zeroes' },
                { text: '173. 二叉搜索树迭代器', link: '/leetcode/173-binary-search-tree-iterator' },
                { text: '174. 地下城游戏', link: '/leetcode/174-dungeon-game' },
                { text: '175. 组合两个表', link: '/leetcode/175-combine-two-tables' },
                { text: '176. 第二高的薪水', link: '/leetcode/176-second-highest-salary' },
                { text: '177. 第 N 高的薪水', link: '/leetcode/177-nth-highest-salary' },
                { text: '178. 分数排名', link: '/leetcode/178-rank-scores' },
                { text: '179. 最大数', link: '/leetcode/179-largest-number' },
                { text: '180. 连续出现的数字', link: '/leetcode/180-consecutive-numbers' },
                { text: '181. 超过经理收入的员工', link: '/leetcode/181-employees-earning-more-than-their-managers' },
                { text: '182. 查找重复的电子邮箱', link: '/leetcode/182-duplicate-emails' },
                { text: '183. 从不订购的客户', link: '/leetcode/183-customers-who-never-order' },
                { text: '184. 部门工资最高的员工', link: '/leetcode/184-department-highest-salary' },
                { text: '185. 部门工资前三高的员工', link: '/leetcode/185-department-top-three-salaries' },
                { text: '186. 反转字符串中的单词 II', link: '/leetcode/186-reverse-words-in-a-string-ii' },
                { text: '187. 重复的 DNA 序列', link: '/leetcode/187-repeated-dna-sequences' },
                { text: '188. 买卖股票的最佳时机 IV', link: '/leetcode/188-best-time-to-buy-and-sell-stock-iv' },
                { text: '189. 轮转数组', link: '/leetcode/189-rotate-array' },
                { text: '190. 颠倒二进制位', link: '/leetcode/190-reverse-bits' },
                { text: '191. 位 1 的个数', link: '/leetcode/191-number-of-1-bits' },
                { text: '192. 统计词频', link: '/leetcode/192-word-frequency' },
                { text: '193. 有效电话号码', link: '/leetcode/193-valid-phone-numbers' },
                { text: '194. 转置文件', link: '/leetcode/194-transpose-file' },
                { text: '195. 第十行', link: '/leetcode/195-tenth-line' },
                { text: '196. 删除重复的电子邮箱', link: '/leetcode/196-delete-duplicate-emails' },
                { text: '197. 上升的温度', link: '/leetcode/197-rising-temperature' },
                { text: '198. 打家劫舍', link: '/leetcode/198-house-robber' },
                { text: '199. 二叉树的右视图', link: '/leetcode/199-binary-tree-right-side-view' },
                { text: '200. 岛屿数量', link: '/leetcode/200-number-of-islands' },
                { text: '201. 数字范围按位与', link: '/leetcode/201-bitwise-and-of-numbers-range' },
                { text: '202. 快乐数', link: '/leetcode/202-happy-number' },
                { text: '203. 移除链表元素', link: '/leetcode/203-remove-linked-list-elements' },
                { text: '204. 计数质数', link: '/leetcode/204-count-primes' },
                { text: '205. 同构字符串', link: '/leetcode/205-isomorphic-strings' },
                { text: '206. 反转链表', link: '/leetcode/206-reverse-linked-list' },
                { text: '207. 课程表', link: '/leetcode/207-course-schedule' },
                { text: '208. 实现 Trie（前缀树）', link: '/leetcode/208-implement-trie-prefix-tree' },
                { text: '209. 长度最小的子数组', link: '/leetcode/209-minimum-size-subarray-sum' },
                { text: '210. 课程表 II', link: '/leetcode/210-course-schedule-ii' },
                { text: '211. 添加与搜索单词 - 数据结构设计', link: '/leetcode/211-design-add-and-search-words-data-structure' },
                { text: '212. 单词搜索 II', link: '/leetcode/212-word-search-ii' },
                { text: '213. 打家劫舍 II', link: '/leetcode/213-house-robber-ii' },
                { text: '214. 最短回文串', link: '/leetcode/214-shortest-palindrome' },
                { text: '215. 数组中的第K个最大元素', link: '/leetcode/215-kth-largest-element-in-an-array' },
                { text: '216. 组合总和 III', link: '/leetcode/216-combination-sum-iii' },
                { text: '217. 存在重复元素', link: '/leetcode/217-contains-duplicate' },
                { text: '218. 天际线问题', link: '/leetcode/218-the-skyline-problem' },
                { text: '219. 存在重复元素 II', link: '/leetcode/219-contains-duplicate-ii' },
                { text: '220. 存在重复元素 III', link: '/leetcode/220-contains-duplicate-iii' },
                { text: '221. 最大正方形', link: '/leetcode/221-maximal-square' },
                { text: '222. 完全二叉树的节点个数', link: '/leetcode/222-count-complete-tree-nodes' },
                { text: '223. 矩形面积', link: '/leetcode/223-rectangle-area' },
                { text: '224. 基本计算器', link: '/leetcode/224-basic-calculator' },
                { text: '225. 用队列实现栈', link: '/leetcode/225-implement-stack-using-queues' },
                { text: '226. 翻转二叉树', link: '/leetcode/226-invert-binary-tree' },
                { text: '227. 基本计算器 II', link: '/leetcode/227-basic-calculator-ii' },
                { text: '228. 汇总区间', link: '/leetcode/228-summary-ranges' },
                { text: '229. 多数元素 II', link: '/leetcode/229-majority-element-ii' },
                { text: '230. 二叉搜索树中第 K 小的元素', link: '/leetcode/230-kth-smallest-element-in-a-bst' },
                { text: '231. 2 的幂', link: '/leetcode/231-power-of-two' },
                { text: '232. 用栈实现队列', link: '/leetcode/232-implement-queue-using-stacks' },
                { text: '233. 数字 1 的个数', link: '/leetcode/233-number-of-digit-one' },
                { text: '234. 回文链表', link: '/leetcode/234-palindrome-linked-list' },
                { text: '235. 二叉搜索树的最近公共祖先', link: '/leetcode/235-lowest-common-ancestor-of-a-binary-search-tree' },
                { text: '236. 二叉树的最近公共祖先', link: '/leetcode/236-lowest-common-ancestor-of-a-binary-tree' },
                { text: '237. 删除链表中的节点', link: '/leetcode/237-delete-node-in-a-linked-list' },
                { text: '238. 除自身以外数组的乘积', link: '/leetcode/238-product-of-array-except-self' },
                { text: '239. 滑动窗口最大值', link: '/leetcode/239-sliding-window-maximum' },
                { text: '240. 搜索二维矩阵 II', link: '/leetcode/240-search-a-2d-matrix-ii' },
                { text: '241. 为运算表达式设计优先级', link: '/leetcode/241-different-ways-to-add-parentheses' },
                { text: '242. 有效的字母异位词', link: '/leetcode/242-valid-anagram' },
                { text: '243. 最短单词距离', link: '/leetcode/243-shortest-word-distance' },
                { text: '244. 最短单词距离 II', link: '/leetcode/244-shortest-word-distance-ii' },
                { text: '245. 最短单词距离 III', link: '/leetcode/245-shortest-word-distance-iii' },
                { text: '246. 中心对称数', link: '/leetcode/246-strobogrammatic-number' },
                { text: '247. 中心对称数 II', link: '/leetcode/247-strobogrammatic-number-ii' },
                { text: '248. 中心对称数 III', link: '/leetcode/248-strobogrammatic-number-iii' },
                { text: '249. 移位字符串分组', link: '/leetcode/249-group-shifted-strings' },
                { text: '250. 统计同值子树', link: '/leetcode/250-count-univalue-subtrees' },
                { text: '251. 展开二维向量', link: '/leetcode/251-flatten-2d-vector' },
                { text: '252. 会议室', link: '/leetcode/252-meeting-rooms' },
                { text: '253. 会议室 II', link: '/leetcode/253-meeting-rooms-ii' },
                { text: '254. 因子的组合', link: '/leetcode/254-factor-combinations' },
                { text: '255. 验证前序遍历序列二叉搜索树', link: '/leetcode/255-verify-preorder-sequence-in-binary-search-tree' },
                { text: '256. 粉刷房子', link: '/leetcode/256-paint-house' },
                { text: '257. 二叉树的所有路径', link: '/leetcode/257-binary-tree-paths' },
                { text: '258. 各位相加', link: '/leetcode/258-add-digits' },
                { text: '259. 较小的三数之和', link: '/leetcode/259-3sum-smaller' },
                { text: '260. 只出现一次的数字 III', link: '/leetcode/260-single-number-iii' },
                { text: '261. 以图判树', link: '/leetcode/261-graph-valid-tree' },
                { text: '262. 行程和用户', link: '/leetcode/262-trips-and-users' },
                { text: '263. 丑数', link: '/leetcode/263-ugly-number' },
                { text: '264. 丑数 II', link: '/leetcode/264-ugly-number-ii' },
                { text: '265. 粉刷房子 II', link: '/leetcode/265-paint-house-ii' },
                { text: '266. 回文排列', link: '/leetcode/266-palindrome-permutation' },
                { text: '267. 回文排列 II', link: '/leetcode/267-palindrome-permutation-ii' },
                { text: '268. 丢失的数字', link: '/leetcode/268-missing-number' },
                { text: '269. 火星词典', link: '/leetcode/269-alien-dictionary' },
                { text: '270. 最接近的二叉搜索树值', link: '/leetcode/270-closest-binary-search-tree-value' },
                { text: '271. 字符串的编码与解码', link: '/leetcode/271-encode-and-decode-strings' },
                { text: '272. 二叉搜索树迭代器 II', link: '/leetcode/272-binary-search-tree-iterator-ii' },
                { text: '273. 整数转换英文表示', link: '/leetcode/273-integer-to-english-words' },
                { text: '274. H 指数', link: '/leetcode/274-h-index' },
                { text: '275. H 指数 II', link: '/leetcode/275-h-index-ii' },
                { text: '276. 栅栏涂色', link: '/leetcode/276-paint-fence' },
                { text: '277. 搜索名人', link: '/leetcode/277-find-the-celebrity' },
                { text: '278. 第一个错误的版本', link: '/leetcode/278-first-bad-version' },
                { text: '279. 完全平方数', link: '/leetcode/279-perfect-squares' },
                { text: '280. 摆动排序', link: '/leetcode/280-wiggle-sort' },
                { text: '281. 锯齿迭代器', link: '/leetcode/281-zigzag-iterator' },
                { text: '282. 给表达式添加运算符', link: '/leetcode/282-expression-add-operators' },
                { text: '283. 移动零', link: '/leetcode/283-move-zeroes' },
                { text: '284. 顶端迭代器', link: '/leetcode/284-peeking-iterator' },
                { text: '285. 二叉搜索树中的中序后继', link: '/leetcode/285-inorder-successor-in-bst' },
                { text: '286. 墙与门', link: '/leetcode/286-walls-and-gates' },
                { text: '287. 寻找重复数', link: '/leetcode/287-find-the-duplicate-number' },
                { text: '288. 单词的唯一缩写', link: '/leetcode/288-unique-word-abbreviation' },
                { text: '289. 生命游戏', link: '/leetcode/289-game-of-life' },
                { text: '290. 单词规律', link: '/leetcode/290-word-pattern' },
                { text: '291. 单词规律 II', link: '/leetcode/291-word-pattern-ii' },
                { text: '292. Nim 游戏', link: '/leetcode/292-nim-game' },
                { text: '293. 翻转游戏', link: '/leetcode/293-flip-game' },
                { text: '294. 翻转游戏 II', link: '/leetcode/294-flip-game-ii' },
                { text: '295. 数据流的中位数', link: '/leetcode/295-find-median-from-data-stream' },
                { text: '296. 最佳碰头地点', link: '/leetcode/296-best-meeting-point' },
                { text: '297. 二叉树的序列化与反序列化', link: '/leetcode/297-serialize-and-deserialize-binary-tree' },
                { text: '298. 二叉树最长连续序列', link: '/leetcode/298-binary-tree-longest-consecutive-sequence' },
                { text: '299. 猜数字游戏', link: '/leetcode/299-bulls-and-cows' },
                { text: '300. 最长递增子序列', link: '/leetcode/300-longest-increasing-subsequence' },
                { text: '301. 删除无效的括号', link: '/leetcode/301-remove-invalid-parentheses' },
                { text: '302. 包围黑点的最小的矩形', link: '/leetcode/302-smallest-rectangle-enclosing-black-pixels' },
                { text: '303. 区域和检索 - 数组不可变', link: '/leetcode/303-range-sum-query-immutable' },
                { text: '304. 二维区域和检索 - 矩阵不可变', link: '/leetcode/304-range-sum-query-2d-immutable' },
                { text: '305. 岛屿的数量 II', link: '/leetcode/305-number-of-islands-ii' },
                { text: '306. 累加数', link: '/leetcode/306-additive-number' },
                { text: '307. 区域和检索 - 数组可修改', link: '/leetcode/307-range-sum-query-mutable' },
                { text: '308. 二维区域和检索 - 可变', link: '/leetcode/308-range-sum-query-2d-mutable' },
                { text: '309. 最佳买卖股票时机含冷冻期', link: '/leetcode/309-best-time-to-buy-and-sell-stock-with-cooldown' },
                { text: '310. 最小高度树', link: '/leetcode/310-minimum-height-trees' },
                { text: '311. 稀疏矩阵的乘法', link: '/leetcode/311-sparse-matrix-multiplication' },
                { text: '312. 戳气球', link: '/leetcode/312-burst-balloons' },
                { text: '313. 超级丑数', link: '/leetcode/313-super-ugly-number' },
                { text: '314. 二叉树的垂直遍历', link: '/leetcode/314-binary-tree-vertical-order-traversal' },
                { text: '315. 计算右侧小于当前元素的个数', link: '/leetcode/315-count-of-smaller-numbers-after-self' },
                { text: '316. 去除重复字母', link: '/leetcode/316-remove-duplicate-letters' },
                { text: '317. 离建筑物最近的距离', link: '/leetcode/317-shortest-distance-from-all-buildings' },
                { text: '318. 最大单词长度乘积', link: '/leetcode/318-maximum-product-of-word-lengths' },
                { text: '319. 灯泡开关', link: '/leetcode/319-bulb-switcher' },
                { text: '320. 广义缩写', link: '/leetcode/320-generalized-abbreviation' },
                { text: '321. 拼接最大数', link: '/leetcode/321-create-maximum-number' },
                { text: '322. 零钱兑换', link: '/leetcode/322-coin-change' },
                { text: '323. 无向图中连通分量的数目', link: '/leetcode/323-number-of-connected-components-in-an-undirected-graph' },
                { text: '324. 摆动排序 II', link: '/leetcode/324-wiggle-sort-ii' },
                { text: '325. 最大子数组之和为 k', link: '/leetcode/325-maximum-size-subarray-sum-equals-k' },
                { text: '326. 3 的幂', link: '/leetcode/326-power-of-three' },
                { text: '327. 区间和的个数', link: '/leetcode/327-count-of-range-sum' },
                { text: '328. 奇偶链表', link: '/leetcode/328-odd-even-linked-list' },
                { text: '329. 矩阵中的最长递增路径', link: '/leetcode/329-longest-increasing-path-in-a-matrix' },
                { text: '330. 按要求补齐数组', link: '/leetcode/330-patching-array' },
                { text: '331. 验证二叉树的前序序列化', link: '/leetcode/331-verify-preorder-serialization-of-a-binary-tree' },
                { text: '332. 重新安排行程', link: '/leetcode/332-reconstruct-itinerary' },
                { text: '333. 最大 BST 子树', link: '/leetcode/333-largest-bst-subtree' },
                { text: '334. 递增的三元子序列', link: '/leetcode/334-increasing-triplet-subsequence' },
                { text: '335. 路径交叉', link: '/leetcode/335-self-crossing' },
                { text: '336. 回文对', link: '/leetcode/336-palindrome-pairs' },
                { text: '337. 打家劫舍 III', link: '/leetcode/337-house-robber-iii' },
                { text: '338. 比特位计数', link: '/leetcode/338-counting-bits' },
                { text: '339. 嵌套列表权重和', link: '/leetcode/339-nested-list-weight-sum' },
                { text: '340. 至多包含 K 个不同字符的最长子串', link: '/leetcode/340-longest-substring-with-at-most-k-distinct-characters' },
                { text: '341. 扁平化嵌套列表迭代器', link: '/leetcode/341-flatten-nested-list-iterator' },
                { text: '342. 4 的幂', link: '/leetcode/342-power-of-four' },
                { text: '343. 整数拆分', link: '/leetcode/343-integer-break' },
                { text: '344. 反转字符串', link: '/leetcode/344-reverse-string' },
                { text: '345. 反转字符串中的元音字母', link: '/leetcode/345-reverse-vowels-of-a-string' },
                { text: '346. 数据流中的移动平均值', link: '/leetcode/346-moving-average-from-data-stream' },
                { text: '347. 前 K 个高频元素', link: '/leetcode/347-top-k-frequent-elements' },
                { text: '348. 设计井字棋', link: '/leetcode/348-design-tic-tac-toe' },
                { text: '349. 两个数组的交集', link: '/leetcode/349-intersection-of-two-arrays' },
                { text: '350. 两个数组的交集 II', link: '/leetcode/350-intersection-of-two-arrays-ii' },
                { text: '351. 安卓系统手势解锁', link: '/leetcode/351-android-unlock-screen' },
                { text: '352. 将数据流变为多个不相交区间', link: '/leetcode/352-data-stream-as-disjoint-intervals' },
                { text: '353. 设计贪吃蛇', link: '/leetcode/353-design-snake-game' },
                { text: '354. 俄罗斯套娃信封问题', link: '/leetcode/354-russian-doll-envelopes' },
                { text: '355. 设计推特', link: '/leetcode/355-design-twitter' },
                { text: '356. 直线镜像', link: '/leetcode/356-line-reflection' },
                { text: '357. 统计各位数字都不同的数字个数', link: '/leetcode/357-count-numbers-with-unique-digits' },
                { text: '358. 重排字符串使得相同字符间距至少为 K', link: '/leetcode/358-rearrange-string-k-distance-apart' },
                { text: '359. 日志速率限制器', link: '/leetcode/359-logger-rate-limiter' },
                { text: '360. 有序转化数组', link: '/leetcode/360-sort-transformed-array' },
                { text: '361. 轰炸敌人', link: '/leetcode/361-bomb-enemy' },
                { text: '362. 设计击球计数器', link: '/leetcode/362-design-hit-counter' },
                { text: '363. 矩形区域不超过 K 的最大数值和', link: '/leetcode/363-max-sum-of-rectangle-no-larger-than-k' },
                { text: '364. 嵌套列表权重和 II', link: '/leetcode/364-nested-list-weight-sum-ii' },
                { text: '365. 水壶问题', link: '/leetcode/365-water-and-jug-problem' },
                { text: '366. 寻找二叉树的叶子节点', link: '/leetcode/366-find-leaves-of-binary-tree' },
                { text: '367. 有效的完全平方数', link: '/leetcode/367-valid-perfect-square' },
                { text: '368. 最大整除子集', link: '/leetcode/368-largest-divisible-subset' },
                { text: '369. 给单链表加一', link: '/leetcode/369-plus-one-linked-list' },
                { text: '370. 区间加法', link: '/leetcode/370-range-addition' },
                { text: '371. 两整数之和', link: '/leetcode/371-sum-of-two-integers' },
                { text: '372. 超级次方', link: '/leetcode/372-super-pow' },
                { text: '373. 查找和最小的 K 对数字', link: '/leetcode/373-find-k-pairs-with-smallest-sums' },
                { text: '374. 猜数字大小', link: '/leetcode/374-guess-number-higher-or-lower' },
                { text: '375. 猜数字大小 II', link: '/leetcode/375-guess-number-higher-or-lower-ii' },
                { text: '376. 摆动序列', link: '/leetcode/376-wiggle-subsequence' },
                { text: '377. 组合总和 Ⅳ', link: '/leetcode/377-combination-sum-iv' },
                { text: '378. 有序矩阵中第 K 小的元素', link: '/leetcode/378-kth-smallest-element-in-a-sorted-matrix' },
                { text: '379. 电话目录管理', link: '/leetcode/379-design-phone-directory' },
                { text: '380. O(1) 时间插入、删除和获取随机元素', link: '/leetcode/380-insert-delete-getrandom-o1' },
                { text: '381. O(1) 时间插入、删除和获取随机元素 - 允许重复', link: '/leetcode/381-insert-delete-getrandom-o1-duplicates-allowed' },
                { text: '382. 链表随机节点', link: '/leetcode/382-linked-list-random-node' },
                { text: '383. 赎金信', link: '/leetcode/383-ransom-note' },
                { text: '384. 打乱数组', link: '/leetcode/384-shuffle-an-array' },
                { text: '385. 迷你语法分析器', link: '/leetcode/385-mini-parser' },
                { text: '386. 字典序排数', link: '/leetcode/386-lexicographical-numbers' },
                { text: '387. 字符串中的第一个唯一字符', link: '/leetcode/387-first-unique-character-in-a-string' },
                { text: '388. 文件的最长绝对路径', link: '/leetcode/388-longest-absolute-file-path' },
                { text: '389. 找不同', link: '/leetcode/389-find-the-difference' },
                { text: '390. 消除游戏', link: '/leetcode/390-elimination-game' },
                { text: '391. 完美矩形', link: '/leetcode/391-perfect-rectangle' },
                { text: '392. 判断子序列', link: '/leetcode/392-is-subsequence' },
                { text: '393. UTF-8 编码验证', link: '/leetcode/393-utf-8-validation' },
                { text: '394. 字符串解码', link: '/leetcode/394-decode-string' },
                { text: '395. 至少有 K 个重复字符的最长子串', link: '/leetcode/395-longest-substring-with-at-least-k-repeating-characters' },
                { text: '396. 旋转函数', link: '/leetcode/396-rotate-function' },
                { text: '397. 整数替换', link: '/leetcode/397-integer-replacement' },
                { text: '398. 随机数索引', link: '/leetcode/398-random-pick-index' },
                { text: '399. 除法求值', link: '/leetcode/399-evaluate-division' },
                { text: '400. 第 N 位数字', link: '/leetcode/400-nth-digit' },
                { text: '401. 二进制手表', link: '/leetcode/401-binary-watch' },
                { text: '402. 移掉 K 位数字', link: '/leetcode/402-remove-k-digits' },
                { text: '403. 青蛙过河', link: '/leetcode/403-frog-jump' },
                { text: '404. 左叶子之和', link: '/leetcode/404-sum-of-left-leaves' },
                { text: '405. 数字转换为十六进制数', link: '/leetcode/405-convert-a-number-to-hexadecimal' },
                { text: '406. 根据身高重建队列', link: '/leetcode/406-queue-reconstruction-by-height' },
                { text: '407. 接雨水 II', link: '/leetcode/407-trapping-rain-water-ii' },
                { text: '408. 有效单词缩写', link: '/leetcode/408-valid-word-abbreviation' },
                { text: '409. 最长回文串', link: '/leetcode/409-longest-palindrome' },
                { text: '410. 分割数组的最大值', link: '/leetcode/410-split-array-largest-sum' },
                { text: '411. 最小唯一单词缩写', link: '/leetcode/411-minimum-unique-word-abbreviation' },
                { text: '412. Fizz Buzz', link: '/leetcode/412-fizz-buzz' },
                { text: '413. 等差数列划分', link: '/leetcode/413-arithmetic-slices' },
                { text: '414. 第三大的数', link: '/leetcode/414-third-maximum-number' },
                { text: '415. 字符串相加', link: '/leetcode/415-add-strings' },
                { text: '416. 分割等和子集', link: '/leetcode/416-partition-equal-subset-sum' },
                { text: '417. 太平洋大西洋水流', link: '/leetcode/417-pacific-atlantic-water-flow' },
                { text: '418. 屏幕可显示句子的数量', link: '/leetcode/418-sentence-screen-fitting' },
                { text: '419. 甲板上的战舰', link: '/leetcode/419-battleships-in-a-board' },
                { text: '420. 强密码检验器', link: '/leetcode/420-strong-password-checker' },
                { text: '421. 数组中两个数的最大异或值', link: '/leetcode/421-maximum-xor-of-two-numbers-in-an-array' },
                { text: '422. 有效的单词方块', link: '/leetcode/422-valid-word-square' },
                { text: '423. 从英文中重建数字', link: '/leetcode/423-reconstruct-original-digits-from-english' },
                { text: '424. 替换后的最长重复字符', link: '/leetcode/424-longest-repeating-character-replacement' },
                { text: '425. 单词方块', link: '/leetcode/425-word-squares' },
                { text: '426. 将二叉搜索树转化为排序的双向链表', link: '/leetcode/426-convert-binary-search-tree-to-sorted-doubly-linked-list' },
                { text: '427. 建立四叉树', link: '/leetcode/427-construct-quad-tree' },
                { text: '428. 序列化和反序列化 N 叉树', link: '/leetcode/428-serialize-and-deserialize-n-ary-tree' },
                { text: '429. N 叉树的层序遍历', link: '/leetcode/429-n-ary-tree-level-order-traversal' },
                { text: '430. 扁平化多级双向链表', link: '/leetcode/430-flatten-a-multilevel-doubly-linked-list' },
                { text: '431. 将 N 叉树编码为二叉树', link: '/leetcode/431-encode-n-ary-tree-to-binary-tree' },
                { text: '432. 全 O(1) 的数据结构', link: '/leetcode/432-all-oone-data-structure' },
                { text: '433. 最小基因变化', link: '/leetcode/433-minimum-genetic-mutation' },
                { text: '434. 字符串中的单词数', link: '/leetcode/434-number-of-segments-in-a-string' },
                { text: '435. 无重叠区间', link: '/leetcode/435-non-overlapping-intervals' },
                { text: '436. 寻找右区间', link: '/leetcode/436-find-right-interval' },
                { text: '437. 路径总和 III', link: '/leetcode/437-path-sum-iii' },
                { text: '438. 找到字符串中所有字母异位词', link: '/leetcode/438-find-all-anagrams-in-a-string' },
                { text: '439. 三元表达式解析器', link: '/leetcode/439-ternary-expression-parser' },
                { text: '440. 字典序的第 K 小数字', link: '/leetcode/440-k-th-smallest-in-lexicographical-order' },
                { text: '441. 排列硬币', link: '/leetcode/441-arranging-coins' },
                { text: '442. 数组中重复的数据', link: '/leetcode/442-find-all-duplicates-in-an-array' },
                { text: '443. 压缩字符串', link: '/leetcode/443-string-compression' },
                { text: '444. 序列重建', link: '/leetcode/444-sequence-reconstruction' },
                { text: '445. 两数相加 II', link: '/leetcode/445-add-two-numbers-ii' },
                { text: '446. 等差数列划分 II - 子序列', link: '/leetcode/446-arithmetic-slices-ii-subsequence' },
                { text: '447. 回旋镖的数量', link: '/leetcode/447-number-of-boomerangs' },
                { text: '448. 找到所有数组中消失的数字', link: '/leetcode/448-find-all-numbers-disappeared-in-an-array' },
                { text: '449. 序列化和反序列化二叉搜索树', link: '/leetcode/449-serialize-and-deserialize-bst' },
                { text: '450. 删除二叉搜索树中的节点', link: '/leetcode/450-delete-node-in-a-bst' },
                { text: '451. 根据字符出现频率排序', link: '/leetcode/451-sort-characters-by-frequency' },
                { text: '452. 用最少数量的箭引爆气球', link: '/leetcode/452-minimum-number-of-arrows-to-burst-balloons' },
                { text: '453. 最小操作次数使数组元素相等', link: '/leetcode/453-minimum-moves-to-equal-array-elements' },
                { text: '454. 四数相加 II', link: '/leetcode/454-4sum-ii' },
                { text: '455. 分发饼干', link: '/leetcode/455-assign-cookies' },
                { text: '456. 132 模式', link: '/leetcode/456-132-pattern' },
                { text: '457. 环形数组循环', link: '/leetcode/457-circular-array-loop' },
                { text: '458. 可怜的小猪', link: '/leetcode/458-poor-pigs' },
                { text: '459. 重复的子字符串', link: '/leetcode/459-repeated-substring-pattern' },
                { text: '460. LFU 缓存', link: '/leetcode/460-lfu-cache' },
                { text: '461. 汉明距离', link: '/leetcode/461-hamming-distance' },
                { text: '462. 最小操作次数使数组元素相等 II', link: '/leetcode/462-minimum-moves-to-equal-array-elements-ii' },
                { text: '463. 岛屿的周长', link: '/leetcode/463-island-perimeter' },
                { text: '464. 我能赢吗', link: '/leetcode/464-can-i-win' },
                { text: '465. 最优账单平衡', link: '/leetcode/465-optimal-account-balancing' },
                { text: '466. 统计重复个数', link: '/leetcode/466-count-the-repetitions' },
                { text: '467. 环绕字符串中唯一的子串', link: '/leetcode/467-unique-substrings-in-wraparound-string' },
                { text: '468. 验证 IP 地址', link: '/leetcode/468-validate-ip-address' },
                { text: '469. 凸多边形', link: '/leetcode/469-convex-polygon' },
                { text: '470. 用 Rand7() 实现 Rand10()', link: '/leetcode/470-implement-rand10-using-rand7' },
                { text: '471. 最短编码', link: '/leetcode/471-encode-string-with-shortest-length' },
                { text: '472. 连接词', link: '/leetcode/472-concatenated-words' },
                { text: '473. 火柴拼正方形', link: '/leetcode/473-matchsticks-to-square' },
                { text: '474. 一和零', link: '/leetcode/474-ones-and-zeroes' },
                { text: '475. 供暖器', link: '/leetcode/475-heaters' },
                { text: '476. 数字的补数', link: '/leetcode/476-number-complement' },
                { text: '477. 总汉明距离', link: '/leetcode/477-total-hamming-distance' },
                { text: '478. 在圆内随机生成点', link: '/leetcode/478-generate-random-point-in-a-circle' },
                { text: '479. 最大回文数乘积', link: '/leetcode/479-largest-palindrome-product' },
                { text: '480. 滑动窗口中位数', link: '/leetcode/480-sliding-window-median' },
                { text: '481. 神奇字符串', link: '/leetcode/481-magical-string' },
                { text: '482. 密钥格式化', link: '/leetcode/482-license-key-formatting' },
                { text: '483. 最小好基数', link: '/leetcode/483-smallest-good-base' },
                { text: '484. 寻找排列', link: '/leetcode/484-find-permutation' },
                { text: '485. 最大连续 1 的个数', link: '/leetcode/485-max-consecutive-ones' },
                { text: '486. 预测赢家', link: '/leetcode/486-predict-the-winner' },
                { text: '487. 最大连续 1 的个数 II', link: '/leetcode/487-max-consecutive-ones-ii' },
                { text: '488. 祖玛游戏', link: '/leetcode/488-zuma-game' },
                { text: '489. 扫地机器人', link: '/leetcode/489-robot-room-cleaner' },
                { text: '490. 迷宫', link: '/leetcode/490-the-maze' },
                { text: '491. 递增子序列', link: '/leetcode/491-increasing-subsequences' },
                { text: '492. 构造矩形', link: '/leetcode/492-construct-the-rectangle' },
                { text: '493. 翻转对', link: '/leetcode/493-reverse-pairs' },
                { text: '494. 目标和', link: '/leetcode/494-target-sum' },
                { text: '495. 提莫攻击', link: '/leetcode/495-teemo-attacking' },
                { text: '496. 下一个更大元素 I', link: '/leetcode/496-next-greater-element-i' },
                { text: '497. 非重叠矩形中的随机点', link: '/leetcode/497-random-point-in-non-overlapping-rectangles' },
                { text: '498. 对角线遍历', link: '/leetcode/498-diagonal-traverse' },
                { text: '499. 迷宫 III', link: '/leetcode/499-the-maze-iii' },
                { text: '500. 键盘行', link: '/leetcode/500-keyboard-row' }
            ]
        },

        {
            text: "剑指 Offer",
            collapsed: true,
            items: [
                { text: 'LCR 001. 两数相除', link: '/lcr/lcr-001-divide-two-integers' },
                { text: 'LCR 002. 二进制求和', link: '/lcr/lcr-002-add-binary' },
                { text: 'LCR 003. 比特位计数', link: '/lcr/lcr-003-counting-bits' },
                { text: 'LCR 004. 只出现一次的数字 II', link: '/lcr/lcr-004-single-number-ii' },
                { text: 'LCR 005. 最大单词长度乘积', link: '/lcr/lcr-005-maximum-product-of-word-lengths' },
                { text: 'LCR 006. 两数之和 II - 输入有序数组', link: '/lcr/lcr-006-two-sum-ii-input-array-is-sorted' },
                { text: 'LCR 007. 三数之和', link: '/lcr/lcr-007-3sum' },
                { text: 'LCR 008. 长度最小的子数组', link: '/lcr/lcr-008-minimum-size-subarray-sum' },
                { text: 'LCR 009. 乘积小于 K 的子数组', link: '/lcr/lcr-009-subarray-product-less-than-k' },
                { text: 'LCR 010. 和为 K 的子数组', link: '/lcr/lcr-010-subarray-sum-equals-k' },
                { text: 'LCR 011. 连续数组', link: '/lcr/lcr-011-contiguous-array' },
                { text: 'LCR 012. 寻找数组的中心下标', link: '/lcr/lcr-012-pivot-index' },
                { text: 'LCR 013. 二维区域和检索 - 矩阵不可变', link: '/lcr/lcr-013-range-sum-query-2d-immutable' },
                { text: 'LCR 014. 字符串的排列', link: '/lcr/lcr-014-permutation-in-string' },
                { text: 'LCR 015. 找到字符串中所有字母异位词', link: '/lcr/lcr-015-find-all-anagrams-in-a-string' },
                { text: 'LCR 016. 无重复字符的最长子串', link: '/lcr/lcr-016-longest-substring-without-repeating-characters' },
                { text: 'LCR 017. 最小覆盖子串', link: '/lcr/lcr-017-minimum-window-substring' },
                { text: 'LCR 018. 验证回文串', link: '/lcr/lcr-018-is-palindrome' },
                { text: 'LCR 019. 验证回文串 II', link: '/lcr/lcr-019-valid-palindrome-ii' },
                { text: 'LCR 020. 回文子串', link: '/lcr/lcr-020-palindromic-substrings' },
                { text: 'LCR 021. 删除链表的倒数第 N 个结点', link: '/lcr/lcr-021-remove-nth-node-from-end-of-list' },
                { text: 'LCR 022. 环形链表 II', link: '/lcr/lcr-022-linked-list-cycle-ii' },
                { text: 'LCR 023. 相交链表', link: '/lcr/lcr-023-intersection-of-two-linked-lists' },
                { text: 'LCR 024. 反转链表', link: '/lcr/lcr-024-reverse-linked-list' },
                { text: 'LCR 025. 两数相加 II', link: '/lcr/lcr-025-add-two-numbers-ii' },
                { text: 'LCR 026. 重排链表', link: '/lcr/lcr-026-reorder-list' },
                { text: 'LCR 027. 回文链表', link: '/lcr/lcr-027-palindrome-linked-list' },
                { text: 'LCR 028. 扁平化多级双向链表', link: '/lcr/lcr-028-flatten-a-multilevel-doubly-linked-list' },
                { text: 'LCR 029. 循环有序列表的插入', link: '/lcr/lcr-029-insert-into-a-sorted-circular-linked-list' },
                { text: 'LCR 030. O(1) 时间插入、删除和获取随机元素', link: '/lcr/lcr-030-insert-delete-getrandom-o1' },
                { text: 'LCR 031. LRU 缓存', link: '/lcr/lcr-031-lru-cache' },
                { text: 'LCR 032. 有效的字母异位词', link: '/lcr/lcr-032-valid-anagram' },
                { text: 'LCR 033. 字母异位词分组', link: '/lcr/lcr-033-group-anagrams' },
                { text: 'LCR 034. 验证外星语词典', link: '/lcr/lcr-034-verifying-an-alien-dictionary' },
                { text: 'LCR 035. 最小时间差', link: '/lcr/lcr-035-minimum-time-difference' },
                { text: 'LCR 036. 逆波兰表达式求值', link: '/lcr/lcr-036-evaluate-reverse-polish-notation' },
                { text: 'LCR 037. 行星碰撞', link: '/lcr/lcr-037-asteroid-collision' },
                { text: 'LCR 038. 每日温度', link: '/lcr/lcr-038-daily-temperatures' },
                { text: 'LCR 039. 柱状图中最大的矩形', link: '/lcr/lcr-039-largest-rectangle-in-histogram' },
                { text: 'LCR 040. 最大矩形', link: '/lcr/lcr-040-maximal-rectangle' },
                { text: 'LCR 041. 数据流中的移动平均值', link: '/lcr/lcr-041-moving-average-from-data-stream' },
                { text: 'LCR 042. 最近的请求次数', link: '/lcr/lcr-042-number-of-recent-calls' },
                { text: 'LCR 043. 完全二叉树插入器', link: '/lcr/lcr-043-complete-binary-tree-inserter' },
                { text: 'LCR 044. 在每个树行中找最大值', link: '/lcr/lcr-044-largest-values-from-labels' },
                { text: 'LCR 045. 找树左下角的值', link: '/lcr/lcr-045-find-bottom-left-tree-value' },
                { text: 'LCR 046. 二叉树的右视图', link: '/lcr/lcr-046-binary-tree-right-side-view' },
                { text: 'LCR 047. 二叉树剪枝', link: '/lcr/lcr-047-binary-tree-pruning' },
                { text: 'LCR 048. 二叉树的序列化与反序列化', link: '/lcr/lcr-048-serialize-and-deserialize-binary-tree' },
                { text: 'LCR 049. 求根节点到叶节点数字之和', link: '/lcr/lcr-049-sum-root-to-leaf-numbers' },
                { text: 'LCR 050. 路径总和 III', link: '/lcr/lcr-050-path-sum-iii' },
                { text: 'LCR 051. 二叉树中的最大路径和', link: '/lcr/lcr-051-binary-tree-maximum-path-sum' },
                { text: 'LCR 052. 递增顺序搜索树', link: '/lcr/lcr-052-increasing-order-search-tree' },
                { text: 'LCR 053. 二叉搜索树中的中序后继', link: '/lcr/lcr-053-inorder-successor-in-bst' },
                { text: 'LCR 054. 把二叉搜索树转换为累加树', link: '/lcr/lcr-054-convert-bst-to-greater-tree' },
                { text: 'LCR 055. 二叉搜索树迭代器', link: '/lcr/lcr-055-bst-iterator' },
                { text: 'LCR 056. 两数之和 IV - 输入二叉搜索树', link: '/lcr/lcr-056-two-sum-iv-input-is-a-bst' },
                { text: 'LCR 057. 存在重复元素 III', link: '/lcr/lcr-057-contains-duplicate-iii' },
                { text: 'LCR 058. 我的日程安排表 I', link: '/lcr/lcr-058-my-calendar-i' },
                { text: 'LCR 059. 数据流中的第 K 大元素', link: '/lcr/lcr-059-kth-largest-element-in-a-stream' },
                { text: 'LCR 060. 前 K 个高频元素', link: '/lcr/lcr-060-top-k-frequent-elements' },
                { text: 'LCR 061. 查找和最小的 K 对数字', link: '/lcr/lcr-061-find-k-pairs-with-smallest-sums' },
                { text: 'LCR 062. 实现 Trie (前缀树)', link: '/lcr/lcr-062-implement-trie-prefix-tree' },
                { text: 'LCR 063. 单词替换', link: '/lcr/lcr-063-replace-words' },
                { text: 'LCR 064. 实现一个魔法字典', link: '/lcr/lcr-064-implement-magic-dictionary' },
                { text: 'LCR 065. 单词的压缩编码', link: '/lcr/lcr-065-short-encoding-of-words' },
                { text: 'LCR 066. 键值映射', link: '/lcr/lcr-066-map-sum-pairs' },
                { text: 'LCR 067. 数组中两个数的最大异或值', link: '/lcr/lcr-067-maximum-xor-of-two-numbers-in-an-array' },
                { text: 'LCR 068. 搜索插入位置', link: '/lcr/lcr-068-search-insert-position' },
                { text: 'LCR 069. 山脉数组的峰顶索引', link: '/lcr/lcr-069-peak-index-in-a-mountain-array' },
                { text: 'LCR 070. 有序数组中的单一元素', link: '/lcr/lcr-070-single-element-in-a-sorted-array' },
                { text: 'LCR 071. 按权重生成随机数', link: '/lcr/lcr-071-random-pick-with-weight' },
                { text: 'LCR 072. x 的平方根', link: '/lcr/lcr-072-sqrtx' },
                { text: 'LCR 073. 爱吃香蕉的狒狒', link: '/lcr/lcr-073-koko-eating-bananas' },
                { text: 'LCR 074. 合并区间', link: '/lcr/lcr-074-merge-intervals' },
                { text: 'LCR 075. 数组的相对排序', link: '/lcr/lcr-075-relative-sort-array' },
                { text: 'LCR 076. 数组中的第 K 个最大元素', link: '/lcr/lcr-076-kth-largest-element-in-an-array' },
                { text: 'LCR 077. 排序链表', link: '/lcr/lcr-077-sort-list' },
                { text: 'LCR 078. 合并 K 个升序链表', link: '/lcr/lcr-078-merge-k-sorted-lists' },
                { text: 'LCR 079. 子集', link: '/lcr/lcr-079-subsets' },
                { text: 'LCR 080. 组合', link: '/lcr/lcr-080-combinations' },
                { text: 'LCR 081. 组合总和', link: '/lcr/lcr-081-combination-sum' },
                { text: 'LCR 082. 组合总和 II', link: '/lcr/lcr-082-combination-sum-ii' },
                { text: 'LCR 083. 全排列', link: '/lcr/lcr-083-permutations' },
                { text: 'LCR 084. 全排列 II', link: '/lcr/lcr-084-permutations-ii' },
                { text: 'LCR 085. 括号生成', link: '/lcr/lcr-085-generate-parentheses' },
                { text: 'LCR 086. 分割回文串', link: '/lcr/lcr-086-palindrome-partitioning' },
                { text: 'LCR 087. 复原 IP 地址', link: '/lcr/lcr-087-restore-ip-addresses' },
                { text: 'LCR 088. 使用最小花费爬楼梯', link: '/lcr/lcr-088-min-cost-climbing-stairs' },
                { text: 'LCR 089. 打家劫舍', link: '/lcr/lcr-089-house-robber' },
                { text: 'LCR 090. 打家劫舍 II', link: '/lcr/lcr-090-house-robber-ii' },
                { text: 'LCR 091. 粉刷房子', link: '/lcr/lcr-091-paint-house' },
                { text: 'LCR 092. 将字符串翻转到单调递增', link: '/lcr/lcr-092-flip-string-to-monotone-increasing' },
                { text: 'LCR 093. 最长的斐波那契子序列的长度', link: '/lcr/lcr-093-length-of-longest-fibonacci-subsequence' },
                { text: 'LCR 094. 分割回文串 II', link: '/lcr/lcr-094-palindrome-partitioning-ii' },
                { text: 'LCR 095. 最长公共子序列', link: '/lcr/lcr-095-longest-common-subsequence' },
                { text: 'LCR 096. 交错字符串', link: '/lcr/lcr-096-interleaving-string' },
                { text: 'LCR 097. 不同的子序列', link: '/lcr/lcr-097-distinct-subsequences' },
                { text: 'LCR 098. 不同路径', link: '/lcr/lcr-098-unique-paths' },
                { text: 'LCR 099. 最小路径和', link: '/lcr/lcr-099-minimum-path-sum' },
                { text: 'LCR 100. 三角形最小路径和', link: '/lcr/lcr-100-triangle' },
                { text: 'LCR 101. 分割等和子集', link: '/lcr/lcr-101-partition-equal-subset-sum' },
                { text: 'LCR 102. 目标和', link: '/lcr/lcr-102-target-sum' },
                { text: 'LCR 103. 零钱兑换', link: '/lcr/lcr-103-coin-change' },
                { text: 'LCR 104. 组合总和 Ⅳ', link: '/lcr/lcr-104-combination-sum-iv' },
                { text: 'LCR 105. 岛屿的最大面积', link: '/lcr/lcr-105-max-area-of-island' },
                { text: 'LCR 106. 判断二分图', link: '/lcr/lcr-106-is-graph-bipartite' },
                { text: 'LCR 107. 01 矩阵', link: '/lcr/lcr-107-01-matrix' },
                { text: 'LCR 108. 单词接龙', link: '/lcr/lcr-108-word-ladder' },
                { text: 'LCR 109. 打开转盘锁', link: '/lcr/lcr-109-open-the-lock' },
                { text: 'LCR 110. 所有可能的路径', link: '/lcr/lcr-110-all-paths-from-source-to-target' },
                { text: 'LCR 111. 除法求值', link: '/lcr/lcr-111-evaluate-division' },
                { text: 'LCR 112. 矩阵中的最长递增路径', link: '/lcr/lcr-112-longest-increasing-path-in-a-matrix' },
                { text: 'LCR 113. 课程表 II', link: '/lcr/lcr-113-course-schedule-ii' },
                { text: 'LCR 114. 火星词典', link: '/lcr/lcr-114-alien-dictionary' },
                { text: 'LCR 115. 序列重建', link: '/lcr/lcr-115-sequence-reconstruction' },
                { text: 'LCR 116. 省份数量', link: '/lcr/lcr-116-number-of-provinces' },
                { text: 'LCR 117. 相似的字符串', link: '/lcr/lcr-117-similar-string-groups' },
                { text: 'LCR 118. 冗余连接', link: '/lcr/lcr-118-redundant-connection' },
                { text: 'LCR 119. 最长连续序列', link: '/lcr/lcr-119-longest-consecutive-sequence' }
            ]
        },

        {
            text: "程序员面试金典",
            collapsed: true,
            items: [
                { text: '面试题 01.01. 判定字符是否唯一', link: '/lcci/lcci-0101-is-unique' },
                { text: '面试题 01.02. 判定是否互为字符重排', link: '/lcci/lcci-0102-check-permutation' },
                { text: '面试题 01.03. URL化', link: '/lcci/lcci-0103-string-to-url' },
                { text: '面试题 01.04. 回文排列', link: '/lcci/lcci-0104-palindrome-permutation' },
                { text: '面试题 01.05. 一次编辑', link: '/lcci/lcci-0105-one-away' },
                { text: '面试题 01.06. 字符串压缩', link: '/lcci/lcci-0106-compress-string' },
                { text: '面试题 01.07. 旋转矩阵', link: '/lcci/lcci-0107-rotate-matrix' },
                { text: '面试题 01.08. 零矩阵', link: '/lcci/lcci-0108-zero-matrix' },
                { text: '面试题 01.09. 字符串轮转', link: '/lcci/lcci-0109-string-rotation' },
                { text: '面试题 02.01. 移除重复节点', link: '/lcci/lcci-0201-remove-duplicate-node' },
                { text: '面试题 02.02. 返回倒数第 k 个节点', link: '/lcci/lcci-0202-kth-node-from-end-of-list' },
                { text: '面试题 02.03. 删除中间节点', link: '/lcci/lcci-0203-delete-middle-node' },
                { text: '面试题 02.04. 分割链表', link: '/lcci/lcci-0204-partition-list' },
                { text: '面试题 02.05. 链表求和', link: '/lcci/lcci-0205-sum-lists' },
                { text: '面试题 02.06. 回文链表', link: '/lcci/lcci-0206-palindrome-linked-list' },
                { text: '面试题 02.07. 链表相交', link: '/lcci/lcci-0207-intersection-of-two-linked-lists' },
                { text: '面试题 02.08. 环路检测', link: '/lcci/lcci-0208-linked-list-cycle' },
                { text: '面试题 03.01. 三合一', link: '/lcci/lcci-0301-three-in-one' },
                { text: '面试题 03.02. 栈的最小值', link: '/lcci/lcci-0302-min-stack' },
                { text: '面试题 03.03. 堆盘子', link: '/lcci/lcci-0303-stack-of-plates' },
                { text: '面试题 03.04. 化栈为队', link: '/lcci/lcci-0304-implement-queue-using-stacks' },
                { text: '面试题 03.05. 栈排序', link: '/lcci/lcci-0305-sort-of-stacks' },
                { text: '面试题 03.06. 动物收容所', link: '/lcci/lcci-0306-animal-shelter' },
                { text: '面试题 04.01. 节点间通路', link: '/lcci/lcci-0401-route-between-nodes' },
                { text: '面试题 04.02. 最小高度树', link: '/lcci/lcci-0402-minimum-height-tree' },
                { text: '面试题 04.03. 特定深度节点链表', link: '/lcci/lcci-0403-list-of-depth' },
                { text: '面试题 04.04. 检查平衡性', link: '/lcci/lcci-0404-check-balance' },
                { text: '面试题 04.05. 合法二叉搜索树', link: '/lcci/lcci-0405-legal-binary-search-tree' },
                { text: '面试题 04.06. 后继者', link: '/lcci/lcci-0406-successor' },
                { text: '面试题 04.08. 首个共同祖先', link: '/lcci/lcci-0408-first-common-ancestor' },
                { text: '面试题 04.09. 二叉搜索树序列', link: '/lcci/lcci-0409-bst-sequences' },
                { text: '面试题 04.10. 检查子树', link: '/lcci/lcci-0410-check-subtree' },
                { text: '面试题 04.12. 求和路径', link: '/lcci/lcci-0412-paths-with-sum' },
                { text: '面试题 05.01. 插入', link: '/lcci/lcci-0501-insert-into-bits' },
                { text: '面试题 05.02. 二进制数转字符串', link: '/lcci/lcci-0502-binary-number-to-string' },
                { text: '面试题 05.03. 翻转数位', link: '/lcci/lcci-0503-reverse-bits' },
                { text: '面试题 05.04. 下一个数', link: '/lcci/lcci-0504-closed-number' },
                { text: '面试题 05.06. 整数转换', link: '/lcci/lcci-0506-convert-integer' },
                { text: '面试题 05.07. 配对交换', link: '/lcci/lcci-0507-exchange' },
                { text: '面试题 05.08. 绘制直线', link: '/lcci/lcci-0508-draw-line' },
                { text: '面试题 08.01. 三步问题', link: '/lcci/lcci-0801-three-steps-problem' },
                { text: '面试题 08.02. 迷路的机器人', link: '/lcci/lcci-0802-robot-in-a-grid' },
                { text: '面试题 08.03. 魔术索引', link: '/lcci/lcci-0803-magic-index' },
                { text: '面试题 08.04. 幂集', link: '/lcci/lcci-0804-power-set' },
                { text: '面试题 08.05. 递归乘法', link: '/lcci/lcci-0805-recursive-mulitply' },
                { text: '面试题 08.06. 汉诺塔问题', link: '/lcci/lcci-0806-hanota' },
                { text: '面试题 08.07. 无重复字符串的排列组合', link: '/lcci/lcci-0807-permutation-i' },
                { text: '面试题 08.08. 零矩阵', link: '/lcci/lcci-0808-zero-matrix' },
                { text: '面试题 08.09. 括号', link: '/lcci/lcci-0809-bracket' },
                { text: '面试题 08.10. 颜色填充', link: '/lcci/lcci-0810-color-fill' },
                { text: '面试题 08.11. 硬币', link: '/lcci/lcci-0811-coin-lcci' },
                { text: '面试题 08.12. 八皇后', link: '/lcci/lcci-0812-eight-queens' },
                { text: '面试题 08.13. 堆箱子', link: '/lcci/lcci-0813-pile-box' },
                { text: '面试题 08.14. 布尔运算', link: '/lcci/lcci-0814-boolean-evaluation' },
                { text: '面试题 16.01. 交换数字', link: '/lcci/lcci-1601-swap-numbers-lcci' },
                { text: '面试题 16.02. 单词频率', link: '/lcci/lcci-1602-word-frequency-lcci' },
                { text: '面试题 16.03. 交点', link: '/lcci/lcci-1603-intersection-lcci' },
                { text: '面试题 16.04. 井字游戏', link: '/lcci/lcci-1604-tic-tac-toe-lcci' },
                { text: '面试题 16.05. 阶乘尾数', link: '/lcci/lcci-1605-factorial-zeros-lcci' },
                { text: '面试题 16.06. 最小差', link: '/lcci/lcci-1606-smallest-difference-lcci' },
                { text: '面试题 16.07. 最大数值', link: '/lcci/lcci-1607-max-lcci' },
                { text: '面试题 16.08. 整数的英语表示', link: '/lcci/lcci-1608-english-int-lcci' },
                { text: '面试题 16.09. 运算', link: '/lcci/lcci-1609-operations-lcci' },
                { text: '面试题 16.10. 生存人数', link: '/lcci/lcci-1610-living-people-lcci' },
                { text: '面试题 16.11. 跳水板', link: '/lcci/lcci-1611-diving-board' },
                { text: '面试题 16.13. 平分正方形', link: '/lcci/lcci-1613-bisect-squares' },
                { text: '面试题 16.14. 最佳直线', link: '/lcci/lcci-1614-best-line' },
                { text: '面试题 16.15. 珠玑妙算', link: '/lcci/lcci-1615-master-mind' },
                { text: '面试题 16.16. 部分排序', link: '/lcci/lcci-1616-sub-sort' },
                { text: '面试题 16.17. 连续数列', link: '/lcci/lcci-1617-contiguous-sequence' },
                { text: '面试题 16.18. 模式匹配', link: '/lcci/lcci-1618-pattern-matching' },
                { text: '面试题 16.19. 水域大小', link: '/lcci/lcci-1619-pond-sizes' },
                { text: '面试题 16.20. T9 键盘', link: '/lcci/lcci-1620-t9-lcci' },
                { text: '面试题 16.21. 交换和', link: '/lcci/lcci-1621-sum-swap-lcci' },
                { text: '面试题 16.22. 兰顿蚂蚁', link: '/lcci/lcci-1622-langtons-ant-lcci' },
                { text: '面试题 16.24. 数对和', link: '/lcci/lcci-1624-pairs-with-sum-lcci' },
                { text: '面试题 16.25. LRU 缓存', link: '/lcci/lcci-1625-lru-cache-lcci' },
                { text: '面试题 16.26. 计算器', link: '/lcci/lcci-1626-calculator-lcci' },
                { text: '面试题 10.01. 合并排序的数组', link: '/lcci/lcci-1001-sorted-merge-lcci' },
                { text: '面试题 10.02. 变位词组', link: '/lcci/lcci-1002-group-anagrams-lcci' },
                { text: '面试题 10.03. 搜索旋转数组', link: '/lcci/lcci-1003-search-rotate-array-lcci' },
                { text: '面试题 10.05. 稀疏数组搜索', link: '/lcci/lcci-1005-sparse-array-search-lcci' },
                { text: '面试题 10.09. 排序矩阵查找', link: '/lcci/lcci-1009-sorted-matrix-search-lcci' },
                { text: '面试题 10.10. 数字流的秩', link: '/lcci/lcci-1010-rank-from-stream-lcci' },
                { text: '面试题 10.11. 峰与谷', link: '/lcci/lcci-1011-peaks-and-valleys-lcci' },
                { text: '面试题 17.01. 不用加号的加法', link: '/lcci/lcci-1701-add-without-plus-lcci' },
                { text: '面试题 17.04. 消失的数字', link: '/lcci/lcci-1704-missing-number-lcci' },
                { text: '面试题 17.05. 字母与数字', link: '/lcci/lcci-1705-letter-and-digit-lcci' },
                { text: '面试题 17.06. 2出现的次数', link: '/lcci/lcci-1706-number-of-2s-in-range-lcci' },
                { text: '面试题 17.07. 婴儿名字', link: '/lcci/lcci-1707-baby-names-lcci' },
                { text: '面试题 17.08. 马戏团人塔', link: '/lcci/lcci-1708-circus-tower-lcci' },
                { text: '面试题 17.09. 第k个数', link: '/lcci/lcci-1709-kth-lexicographical-number-lcci' },
                { text: '面试题 17.10. 主要元素', link: '/lcci/lcci-1710-majority-element-lcci' },
                { text: '面试题 17.11. 单词距离', link: '/lcci/lcci-1711-find-closest-lcci' },
                { text: '面试题 17.12. BiNode', link: '/lcci/lcci-1712-binode-lcci' },
                { text: '面试题 17.13. 恢复空格', link: '/lcci/lcci-1713-re-space-lcci' },
                { text: '面试题 17.14. 最小K个数', link: '/lcci/lcci-1714-smallest-k-lcci' },
                { text: '面试题 17.15. 最长单词', link: '/lcci/lcci-1715-longest-word-lcci' },
                { text: '面试题 17.16. 按摩师', link: '/lcci/lcci-1716-the-masseuse-lcci' },
                { text: '面试题 17.17. 多次搜索', link: '/lcci/lcci-1717-multi-search-lcci' },
                { text: '面试题 17.18. 最短超串', link: '/lcci/lcci-1718-shortest-supersequence-lcci' },
                { text: '面试题 17.19. 消失的两个数字', link: '/lcci/lcci-1719-missing-two-lcci' },
                { text: '面试题 17.20. 连续中值', link: '/lcci/lcci-1720-continuous-median-lcci' },
                { text: '面试题 17.21. 直方图的水量', link: '/lcci/lcci-1721-volume-of-histogram-lcci' },
                { text: '面试题 17.22. 单词转换', link: '/lcci/lcci-1722-word-transformer-lcci' },
                { text: '面试题 17.23. 最大黑方阵', link: '/lcci/lcci-1723-max-black-square-lcci' },
                { text: '面试题 17.24. 最大子矩阵', link: '/lcci/lcci-1724-max-submatrix-lcci' },
                { text: '面试题 17.25. 单词矩阵', link: '/lcci/lcci-1725-word-rectangle-lcci' },
                { text: '面试题 17.26. 稀疏相似度', link: '/lcci/lcci-1726-sparse-similarity-lcci' }
            ]
        }
    ],
}
