import type { DefaultTheme } from 'vitepress'

export const sidebar: DefaultTheme.Config['sidebar'] = {

    '/': [
        { text: "学习路径", link: "/guide" },
        {
            text: "LeetCode",
            collapsed: true,
            items: [
                { text: '1. 两数之和', link: '/leetcode/1-two-sum' },
                { text: '2. 两数相加', link: '/leetcode/2-add-two-numbers' },
                { text: '3. 无重复字符的最长子串', link: '/leetcode/3-longest-substring-without-repeating-characters' },
                { text: '4. 寻找两个正序数组的中位数', link: '/leetcode/4-median-of-two-sorted-arrays' },
                { text: '5. 最长回文子串', link: '/leetcode/5-longest-palindromic-substring' },
                { text: '6. Z 字形变换', link: '/leetcode/6-zigzag-conversion' },
                { text: '7. 整数反转', link: '/leetcode/7-reverse-integer' },
                { text: '8. 字符串转换整数 (atoi)', link: '/leetcode/8-string-to-integer-atoi' },
                { text: '9. 回文数', link: '/leetcode/9-palindrome-number' },
                { text: '10. 正则表达式匹配', link: '/leetcode/10-regular-expression-matching' },
                { text: '11. 盛最多水的容器', link: '/leetcode/11-container-with-most-water' },
                { text: '12. 整数转罗马数字', link: '/leetcode/12-integer-to-roman' },
                { text: '13. 罗马数字转整数', link: '/leetcode/13-roman-to-integer' },
                { text: '14. 最长公共前缀', link: '/leetcode/14-longest-common-prefix' },
                { text: '15. 三数之和', link: '/leetcode/15-3sum' },
                { text: '16. 最接近的三数之和', link: '/leetcode/16-3sum-closest' },
                { text: '17. 电话号码的字母组合', link: '/leetcode/17-letter-combinations-of-a-phone-number' },
                { text: '18. 四数之和', link: '/leetcode/18-4sum' },
                { text: '19. 删除链表的倒数第 N 个结点', link: '/leetcode/19-remove-nth-node-from-end-of-list' },
                { text: '20. 有效的括号', link: '/leetcode/20-valid-parentheses' },
                { text: '21. 合并两个有序链表', link: '/leetcode/21-merge-two-sorted-lists' },
                { text: '22. 括号生成', link: '/leetcode/22-generate-parentheses' },
                { text: '23. 合并 K 个升序链表', link: '/leetcode/23-merge-k-sorted-lists' },
                { text: '24. 两两交换链表中的节点', link: '/leetcode/24-swap-nodes-in-pairs' },
                { text: '25. K 个一组翻转链表', link: '/leetcode/25-reverse-nodes-in-k-group' },
                { text: '26. 删除有序数组中的重复项', link: '/leetcode/26-remove-duplicates-from-sorted-array' },
                { text: '27. 移除元素', link: '/leetcode/27-remove-element' },
                { text: '28. 找出字符串中第一个匹配项的下标', link: '/leetcode/28-find-the-index-of-the-first-occurrence-in-a-string' },
                { text: '29. 两数相除', link: '/leetcode/29-divide-two-integers' },
                { text: '30. 串联所有单词的子串', link: '/leetcode/30-substring-with-concatenation-of-all-words' },
                { text: '31. 下一个排列', link: '/leetcode/31-next-permutation' },
                { text: '32. 最长有效括号', link: '/leetcode/32-longest-valid-parentheses' },
                { text: '33. 搜索旋转排序数组', link: '/leetcode/33-search-in-rotated-sorted-array' },
                { text: '34. 在排序数组中查找元素的第一个和最后一个位置', link: '/leetcode/34-find-first-and-last-position-of-element-in-sorted-array' },
                { text: '35. 搜索插入位置', link: '/leetcode/35-search-insert-position' },
                { text: '36. 有效的数独', link: '/leetcode/36-valid-sudoku' },
                { text: '37. 解数独', link: '/leetcode/37-sudoku-solver' },
                { text: '38. 外观数列', link: '/leetcode/38-count-and-say' },
                { text: '39. 组合总和', link: '/leetcode/39-combination-sum' },
                { text: '40. 组合总和 II', link: '/leetcode/40-combination-sum-ii' },
                { text: '41. 缺失的第一个正数', link: '/leetcode/41-first-missing-positive' },
                { text: '42. 接雨水', link: '/leetcode/42-trapping-rain-water' },
                { text: '43. 字符串相乘', link: '/leetcode/43-multiply-strings' },
                { text: '44. 通配符匹配', link: '/leetcode/44-wildcard-matching' },
                { text: '45. 跳跃游戏 II', link: '/leetcode/45-jump-game-ii' },
                { text: '46. 全排列', link: '/leetcode/46-permutations' },
                { text: '47. 全排列 II', link: '/leetcode/47-permutations-ii' },
                { text: '48. 旋转图像', link: '/leetcode/48-rotate-image' },
                { text: '49. 字母异位词分组', link: '/leetcode/49-group-anagrams' },
                { text: '50. Pow(x, n)', link: '/leetcode/50-powx-n' },
                { text: '51. N 皇后', link: '/leetcode/51-n-queens' },
                { text: '52. N 皇后 II', link: '/leetcode/52-n-queens-ii' },
                { text: '53. 最大子数组和', link: '/leetcode/53-maximum-subarray' },
                { text: '54. 螺旋矩阵', link: '/leetcode/54-spiral-matrix' },
                { text: '55. 跳跃游戏', link: '/leetcode/55-jump-game' },
                { text: '56. 合并区间', link: '/leetcode/56-merge-intervals' },
                { text: '57. 插入区间', link: '/leetcode/57-insert-interval' },
                { text: '58. 最后一个单词的长度', link: '/leetcode/58-length-of-last-word' },
                { text: '59. 螺旋矩阵 II', link: '/leetcode/59-spiral-matrix-ii' },
                { text: '60. 排列序列', link: '/leetcode/60-permutation-sequence' },
                { text: '61. 旋转链表', link: '/leetcode/61-rotate-list' },
                { text: '62. 不同路径', link: '/leetcode/62-unique-paths' },
                { text: '63. 不同路径 II', link: '/leetcode/63-unique-paths-ii' },
                { text: '64. 最小路径和', link: '/leetcode/64-minimum-path-sum' },
                { text: '65. 有效数字', link: '/leetcode/65-valid-number' },
                { text: '66. 加一', link: '/leetcode/66-plus-one' },
                { text: '67. 二进制求和', link: '/leetcode/67-add-binary' },
                { text: '68. 文本左右对齐', link: '/leetcode/68-text-justification' },
                { text: '69. x 的平方根', link: '/leetcode/69-sqrtx' },
                { text: '70. 爬楼梯', link: '/leetcode/70-climbing-stairs' },
                { text: '71. 简化路径', link: '/leetcode/71-simplify-path' },
                { text: '72. 编辑距离', link: '/leetcode/72-edit-distance' },
                { text: '73. 矩阵置零', link: '/leetcode/73-set-matrix-zeroes' },
                { text: '74. 搜索二维矩阵', link: '/leetcode/74-search-a-2d-matrix' },
                { text: '75. 颜色分类', link: '/leetcode/75-sort-colors' },
                { text: '76. 最小覆盖子串', link: '/leetcode/76-minimum-window-substring' },
                { text: '77. 组合', link: '/leetcode/77-combinations' },
                { text: '78. 子集', link: '/leetcode/78-subsets' },
                { text: '79. 单词搜索', link: '/leetcode/79-word-search' },
                { text: '80. 删除有序数组中的重复项 II', link: '/leetcode/80-remove-duplicates-from-sorted-array-ii' },
                { text: '81. 搜索旋转排序数组 II', link: '/leetcode/81-search-in-rotated-sorted-array-ii' },
                { text: '82. 删除排序链表中的重复元素 II', link: '/leetcode/82-remove-duplicates-from-sorted-list-ii' },
                { text: '83. 删除排序链表中的重复元素', link: '/leetcode/83-remove-duplicates-from-sorted-list' },
                { text: '84. 柱状图中最大的矩形', link: '/leetcode/84-largest-rectangle-in-histogram' },
                { text: '85. 最大矩形', link: '/leetcode/85-maximal-rectangle' },
                { text: '86. 分隔链表', link: '/leetcode/86-partition-list' },
                { text: '87. 扰乱字符串', link: '/leetcode/87-scramble-string' },
                { text: '88. 合并两个有序数组', link: '/leetcode/88-merge-sorted-array' },
                { text: '89. 格雷编码', link: '/leetcode/89-gray-code' },
                { text: '90. 子集 II', link: '/leetcode/90-subsets-ii' },
                { text: '91. 解码方法', link: '/leetcode/91-decode-ways' },
                { text: '92. 反转链表 II', link: '/leetcode/92-reverse-linked-list-ii' },
                { text: '93. 复原 IP 地址', link: '/leetcode/93-restore-ip-addresses' },
                { text: '94. 二叉树的中序遍历', link: '/leetcode/94-binary-tree-inorder-traversal' },
                { text: '95. 不同的二叉搜索树 II', link: '/leetcode/95-unique-binary-search-trees-ii' },
                { text: '96. 不同的二叉搜索树', link: '/leetcode/96-unique-binary-search-trees' },
                { text: '97. 交错字符串', link: '/leetcode/97-interleaving-string' },
                { text: '98. 验证二叉搜索树', link: '/leetcode/98-validate-binary-search-tree' },
                { text: '99. 恢复二叉搜索树', link: '/leetcode/99-recover-binary-search-tree' },
                { text: '100. 相同的树', link: '/leetcode/100-same-tree' },
                { text: '101. 对称二叉树', link: '/leetcode/101-symmetric-tree' },
                { text: '102. 二叉树的层序遍历', link: '/leetcode/102-binary-tree-level-order-traversal' },
                { text: '103. 二叉树的锯齿形层序遍历', link: '/leetcode/103-binary-tree-zigzag-level-order-traversal' },
                { text: '104. 二叉树的最大深度', link: '/leetcode/104-maximum-depth-of-binary-tree' },
                { text: '105. 从前序与中序遍历序列构造二叉树', link: '/leetcode/105-construct-binary-tree-from-preorder-and-inorder-traversal' },
                { text: '106. 从中序与后序遍历序列构造二叉树', link: '/leetcode/106-construct-binary-tree-from-inorder-and-postorder-traversal' },
                { text: '107. 二叉树的层序遍历 II', link: '/leetcode/107-binary-tree-level-order-traversal-ii' },
                { text: '108. 将有序数组转换为二叉搜索树', link: '/leetcode/108-convert-sorted-array-to-binary-search-tree' },
                { text: '109. 有序链表转换二叉搜索树', link: '/leetcode/109-convert-sorted-list-to-binary-search-tree' },
                { text: '110. 平衡二叉树', link: '/leetcode/110-balanced-binary-tree' },
                { text: '111. 二叉树的最小深度', link: '/leetcode/111-minimum-depth-of-binary-tree' },
                { text: '112. 路径总和', link: '/leetcode/112-path-sum' },
                { text: '113. 路径总和 II', link: '/leetcode/113-path-sum-ii' },
                { text: '114. 二叉树展开为链表', link: '/leetcode/114-flatten-binary-tree-to-linked-list' },
                { text: '115. 不同的子序列', link: '/leetcode/115-distinct-subsequences' },
                { text: '116. 填充每个节点的下一个右侧节点指针', link: '/leetcode/116-populating-next-right-pointers-in-each-node' },
                { text: '117. 填充每个节点的下一个右侧节点指针 II', link: '/leetcode/117-populating-next-right-pointers-in-each-node-ii' },
                { text: '118. 杨辉三角', link: '/leetcode/118-pascals-triangle' },
                { text: '119. 杨辉三角 II', link: '/leetcode/119-pascals-triangle-ii' },
                { text: '120. 三角形最小路径和', link: '/leetcode/120-triangle' },
                { text: '121. 买卖股票的最佳时机', link: '/leetcode/121-best-time-to-buy-and-sell-stock' },
                { text: '122. 买卖股票的最佳时机 II', link: '/leetcode/122-best-time-to-buy-and-sell-stock-ii' },
                { text: '123. 买卖股票的最佳时机 III', link: '/leetcode/123-best-time-to-buy-and-sell-stock-iii' },
                { text: '124. 二叉树中的最大路径和', link: '/leetcode/124-binary-tree-maximum-path-sum' },
                { text: '125. 验证回文串', link: '/leetcode/125-valid-palindrome' },
                { text: '126. 单词接龙 II', link: '/leetcode/126-word-ladder-ii' },
                { text: '127. 单词接龙', link: '/leetcode/127-word-ladder' },
                { text: '128. 最长连续序列', link: '/leetcode/128-longest-consecutive-sequence' },
                { text: '129. 求根节点到叶节点数字之和', link: '/leetcode/129-sum-root-to-leaf-numbers' },
                { text: '130. 被围绕的区域', link: '/leetcode/130-surrounded-regions' },
                { text: '131. 分割回文串', link: '/leetcode/131-palindrome-partitioning' },
                { text: '132. 分割回文串 II', link: '/leetcode/132-palindrome-partitioning-ii' },
                { text: '133. 克隆图', link: '/leetcode/133-clone-graph' },
                { text: '134. 加油站', link: '/leetcode/134-gas-station' },
                { text: '135. 分发糖果', link: '/leetcode/135-candy' },
                { text: '136. 只出现一次的数字', link: '/leetcode/136-single-number' },
                { text: '137. 只出现一次的数字 II', link: '/leetcode/137-single-number-ii' },
                { text: '138. 随机链表的复制', link: '/leetcode/138-copy-list-with-random-pointer' },
                { text: '139. 单词拆分', link: '/leetcode/139-word-break' },
                { text: '140. 单词拆分 II', link: '/leetcode/140-word-break-ii' }
            ]
        },

        {
            text: "剑指 Offer",
            collapsed: true,
            items: [
                { text: 'LCR 001. 两数相除', link: '/lcr/lcr-001-divide-two-integers' },
                { text: 'LCR 002. 二进制求和', link: '/lcr/lcr-002-add-binary' },
                { text: 'LCR 003. 比特位计数', link: '/lcr/lcr-003-counting-bits' },
                { text: 'LCR 004. 只出现一次的数字 II', link: '/lcr/lcr-004-single-number-ii' },
                { text: 'LCR 005. 最大单词长度乘积', link: '/lcr/lcr-005-maximum-product-of-word-lengths' },
                { text: 'LCR 006. 两数之和 II - 输入有序数组', link: '/lcr/lcr-006-two-sum-ii-input-array-is-sorted' },
                { text: 'LCR 007. 三数之和', link: '/lcr/lcr-007-3sum' },
                { text: 'LCR 008. 长度最小的子数组', link: '/lcr/lcr-008-minimum-size-subarray-sum' },
                { text: 'LCR 009. 乘积小于 K 的子数组', link: '/lcr/lcr-009-subarray-product-less-than-k' },
                { text: 'LCR 010. 和为 K 的子数组', link: '/lcr/lcr-010-subarray-sum-equals-k' },
                { text: 'LCR 011. 连续数组', link: '/lcr/lcr-011-contiguous-array' },
                { text: 'LCR 012. 寻找数组的中心下标', link: '/lcr/lcr-012-pivot-index' },
                { text: 'LCR 013. 二维区域和检索 - 矩阵不可变', link: '/lcr/lcr-013-range-sum-query-2d-immutable' },
                { text: 'LCR 014. 字符串的排列', link: '/lcr/lcr-014-permutation-in-string' },
                { text: 'LCR 015. 找到字符串中所有字母异位词', link: '/lcr/lcr-015-find-all-anagrams-in-a-string' },
                { text: 'LCR 016. 无重复字符的最长子串', link: '/lcr/lcr-016-longest-substring-without-repeating-characters' },
                { text: 'LCR 017. 最小覆盖子串', link: '/lcr/lcr-017-minimum-window-substring' },
                { text: 'LCR 018. 验证回文串', link: '/lcr/lcr-018-is-palindrome' },
                { text: 'LCR 019. 验证回文串 II', link: '/lcr/lcr-019-valid-palindrome-ii' },
                { text: 'LCR 020. 回文子串', link: '/lcr/lcr-020-palindromic-substrings' },
                { text: 'LCR 021. 删除链表的倒数第 N 个结点', link: '/lcr/lcr-021-remove-nth-node-from-end-of-list' },
                { text: 'LCR 022. 环形链表 II', link: '/lcr/lcr-022-linked-list-cycle-ii' },
                { text: 'LCR 023. 相交链表', link: '/lcr/lcr-023-intersection-of-two-linked-lists' },
                { text: 'LCR 024. 反转链表', link: '/lcr/lcr-024-reverse-linked-list' },
                { text: 'LCR 025. 两数相加 II', link: '/lcr/lcr-025-add-two-numbers-ii' },
                { text: 'LCR 026. 重排链表', link: '/lcr/lcr-026-reorder-list' },
                { text: 'LCR 027. 回文链表', link: '/lcr/lcr-027-palindrome-linked-list' },
                { text: 'LCR 028. 扁平化多级双向链表', link: '/lcr/lcr-028-flatten-a-multilevel-doubly-linked-list' },
                { text: 'LCR 029. 循环有序列表的插入', link: '/lcr/lcr-029-insert-into-a-sorted-circular-linked-list' },
                { text: 'LCR 030. O(1) 时间插入、删除和获取随机元素', link: '/lcr/lcr-030-insert-delete-getrandom-o1' },
                { text: 'LCR 031. LRU 缓存', link: '/lcr/lcr-031-lru-cache' },
                { text: 'LCR 032. 有效的字母异位词', link: '/lcr/lcr-032-valid-anagram' },
                { text: 'LCR 033. 字母异位词分组', link: '/lcr/lcr-033-group-anagrams' },
                { text: 'LCR 034. 验证外星语词典', link: '/lcr/lcr-034-verifying-an-alien-dictionary' },
                { text: 'LCR 035. 最小时间差', link: '/lcr/lcr-035-minimum-time-difference' },
                { text: 'LCR 036. 逆波兰表达式求值', link: '/lcr/lcr-036-evaluate-reverse-polish-notation' },
                { text: 'LCR 037. 行星碰撞', link: '/lcr/lcr-037-asteroid-collision' },
                { text: 'LCR 038. 每日温度', link: '/lcr/lcr-038-daily-temperatures' },
                { text: 'LCR 039. 柱状图中最大的矩形', link: '/lcr/lcr-039-largest-rectangle-in-histogram' },
                { text: 'LCR 040. 最大矩形', link: '/lcr/lcr-040-maximal-rectangle' },
                { text: 'LCR 041. 数据流中的移动平均值', link: '/lcr/lcr-041-moving-average-from-data-stream' },
                { text: 'LCR 042. 最近的请求次数', link: '/lcr/lcr-042-number-of-recent-calls' },
                { text: 'LCR 043. 完全二叉树插入器', link: '/lcr/lcr-043-complete-binary-tree-inserter' },
                { text: 'LCR 044. 在每个树行中找最大值', link: '/lcr/lcr-044-largest-values-from-labels' },
                { text: 'LCR 045. 找树左下角的值', link: '/lcr/lcr-045-find-bottom-left-tree-value' },
                { text: 'LCR 046. 二叉树的右视图', link: '/lcr/lcr-046-binary-tree-right-side-view' },
                { text: 'LCR 047. 二叉树剪枝', link: '/lcr/lcr-047-binary-tree-pruning' },
                { text: 'LCR 048. 二叉树的序列化与反序列化', link: '/lcr/lcr-048-serialize-and-deserialize-binary-tree' },
                { text: 'LCR 049. 求根节点到叶节点数字之和', link: '/lcr/lcr-049-sum-root-to-leaf-numbers' },
                { text: 'LCR 050. 路径总和 III', link: '/lcr/lcr-050-path-sum-iii' },
                { text: 'LCR 051. 二叉树中的最大路径和', link: '/lcr/lcr-051-binary-tree-maximum-path-sum' },
                { text: 'LCR 052. 递增顺序搜索树', link: '/lcr/lcr-052-increasing-order-search-tree' },
                { text: 'LCR 053. 二叉搜索树中的中序后继', link: '/lcr/lcr-053-inorder-successor-in-bst' },
                { text: 'LCR 054. 把二叉搜索树转换为累加树', link: '/lcr/lcr-054-convert-bst-to-greater-tree' },
                { text: 'LCR 055. 二叉搜索树迭代器', link: '/lcr/lcr-055-bst-iterator' },
                { text: 'LCR 056. 两数之和 IV - 输入二叉搜索树', link: '/lcr/lcr-056-two-sum-iv-input-is-a-bst' },
                { text: 'LCR 057. 存在重复元素 III', link: '/lcr/lcr-057-contains-duplicate-iii' },
                { text: 'LCR 058. 我的日程安排表 I', link: '/lcr/lcr-058-my-calendar-i' },
                { text: 'LCR 059. 数据流中的第 K 大元素', link: '/lcr/lcr-059-kth-largest-element-in-a-stream' },
                { text: 'LCR 060. 前 K 个高频元素', link: '/lcr/lcr-060-top-k-frequent-elements' },
                { text: 'LCR 061. 查找和最小的 K 对数字', link: '/lcr/lcr-061-find-k-pairs-with-smallest-sums' },
                { text: 'LCR 062. 实现 Trie (前缀树)', link: '/lcr/lcr-062-implement-trie-prefix-tree' },
                { text: 'LCR 063. 单词替换', link: '/lcr/lcr-063-replace-words' },
                { text: 'LCR 064. 实现一个魔法字典', link: '/lcr/lcr-064-implement-magic-dictionary' },
                { text: 'LCR 065. 单词的压缩编码', link: '/lcr/lcr-065-short-encoding-of-words' },
                { text: 'LCR 066. 键值映射', link: '/lcr/lcr-066-map-sum-pairs' },
                { text: 'LCR 067. 数组中两个数的最大异或值', link: '/lcr/lcr-067-maximum-xor-of-two-numbers-in-an-array' },
                { text: 'LCR 068. 搜索插入位置', link: '/lcr/lcr-068-search-insert-position' },
                { text: 'LCR 069. 山脉数组的峰顶索引', link: '/lcr/lcr-069-peak-index-in-a-mountain-array' },
                { text: 'LCR 070. 有序数组中的单一元素', link: '/lcr/lcr-070-single-element-in-a-sorted-array' },
                { text: 'LCR 071. 按权重生成随机数', link: '/lcr/lcr-071-random-pick-with-weight' },
                { text: 'LCR 072. x 的平方根', link: '/lcr/lcr-072-sqrtx' },
                { text: 'LCR 073. 爱吃香蕉的狒狒', link: '/lcr/lcr-073-koko-eating-bananas' },
                { text: 'LCR 074. 合并区间', link: '/lcr/lcr-074-merge-intervals' },
                { text: 'LCR 075. 数组的相对排序', link: '/lcr/lcr-075-relative-sort-array' },
                { text: 'LCR 076. 数组中的第 K 个最大元素', link: '/lcr/lcr-076-kth-largest-element-in-an-array' },
                { text: 'LCR 077. 排序链表', link: '/lcr/lcr-077-sort-list' },
                { text: 'LCR 078. 合并 K 个升序链表', link: '/lcr/lcr-078-merge-k-sorted-lists' },
                { text: 'LCR 079. 子集', link: '/lcr/lcr-079-subsets' },
                { text: 'LCR 080. 组合', link: '/lcr/lcr-080-combinations' },
                { text: 'LCR 081. 组合总和', link: '/lcr/lcr-081-combination-sum' },
                { text: 'LCR 082. 组合总和 II', link: '/lcr/lcr-082-combination-sum-ii' },
                { text: 'LCR 083. 全排列', link: '/lcr/lcr-083-permutations' },
                { text: 'LCR 084. 全排列 II', link: '/lcr/lcr-084-permutations-ii' },
                { text: 'LCR 085. 括号生成', link: '/lcr/lcr-085-generate-parentheses' },
                { text: 'LCR 086. 分割回文串', link: '/lcr/lcr-086-palindrome-partitioning' },
                { text: 'LCR 087. 复原 IP 地址', link: '/lcr/lcr-087-restore-ip-addresses' },
                { text: 'LCR 088. 使用最小花费爬楼梯', link: '/lcr/lcr-088-min-cost-climbing-stairs' },
                { text: 'LCR 089. 打家劫舍', link: '/lcr/lcr-089-house-robber' },
                { text: 'LCR 090. 打家劫舍 II', link: '/lcr/lcr-090-house-robber-ii' },
                { text: 'LCR 091. 粉刷房子', link: '/lcr/lcr-091-paint-house' },
                { text: 'LCR 092. 将字符串翻转到单调递增', link: '/lcr/lcr-092-flip-string-to-monotone-increasing' },
                { text: 'LCR 093. 最长的斐波那契子序列的长度', link: '/lcr/lcr-093-length-of-longest-fibonacci-subsequence' },
                { text: 'LCR 094. 分割回文串 II', link: '/lcr/lcr-094-palindrome-partitioning-ii' },
                { text: 'LCR 095. 最长公共子序列', link: '/lcr/lcr-095-longest-common-subsequence' },
                { text: 'LCR 096. 交错字符串', link: '/lcr/lcr-096-interleaving-string' },
                { text: 'LCR 097. 不同的子序列', link: '/lcr/lcr-097-distinct-subsequences' },
                { text: 'LCR 098. 不同路径', link: '/lcr/lcr-098-unique-paths' },
                { text: 'LCR 099. 最小路径和', link: '/lcr/lcr-099-minimum-path-sum' },
                { text: 'LCR 100. 三角形最小路径和', link: '/lcr/lcr-100-triangle' },
                { text: 'LCR 101. 分割等和子集', link: '/lcr/lcr-101-partition-equal-subset-sum' },
                { text: 'LCR 102. 目标和', link: '/lcr/lcr-102-target-sum' },
                { text: 'LCR 103. 零钱兑换', link: '/lcr/lcr-103-coin-change' },
                { text: 'LCR 104. 组合总和 Ⅳ', link: '/lcr/lcr-104-combination-sum-iv' },
                { text: 'LCR 105. 岛屿的最大面积', link: '/lcr/lcr-105-max-area-of-island' },
                { text: 'LCR 106. 判断二分图', link: '/lcr/lcr-106-is-graph-bipartite' },
                { text: 'LCR 107. 01 矩阵', link: '/lcr/lcr-107-01-matrix' },
                { text: 'LCR 108. 单词接龙', link: '/lcr/lcr-108-word-ladder' },
                { text: 'LCR 109. 打开转盘锁', link: '/lcr/lcr-109-open-the-lock' },
                { text: 'LCR 110. 所有可能的路径', link: '/lcr/lcr-110-all-paths-from-source-to-target' },
                { text: 'LCR 111. 除法求值', link: '/lcr/lcr-111-evaluate-division' },
                { text: 'LCR 112. 矩阵中的最长递增路径', link: '/lcr/lcr-112-longest-increasing-path-in-a-matrix' },
                { text: 'LCR 113. 课程表 II', link: '/lcr/lcr-113-course-schedule-ii' },
                { text: 'LCR 114. 火星词典', link: '/lcr/lcr-114-alien-dictionary' },
                { text: 'LCR 115. 序列重建', link: '/lcr/lcr-115-sequence-reconstruction' },
                { text: 'LCR 116. 省份数量', link: '/lcr/lcr-116-number-of-provinces' },
                { text: 'LCR 117. 相似的字符串', link: '/lcr/lcr-117-similar-string-groups' },
                { text: 'LCR 118. 冗余连接', link: '/lcr/lcr-118-redundant-connection' },
                { text: 'LCR 119. 最长连续序列', link: '/lcr/lcr-119-longest-consecutive-sequence' }
            ]
        },

        {
            text: "程序员面试金典",
            collapsed: true,
            items: [
                { text: '面试题 01.01. 判定字符是否唯一', link: '/lcci/lcci-0101-is-unique' },
                { text: '面试题 01.02. 判定是否互为字符重排', link: '/lcci/lcci-0102-check-permutation' },
                { text: '面试题 01.03. URL化', link: '/lcci/lcci-0103-string-to-url' },
                { text: '面试题 01.04. 回文排列', link: '/lcci/lcci-0104-palindrome-permutation' },
                { text: '面试题 01.05. 一次编辑', link: '/lcci/lcci-0105-one-away' },
                { text: '面试题 01.06. 字符串压缩', link: '/lcci/lcci-0106-compress-string' },
                { text: '面试题 01.07. 旋转矩阵', link: '/lcci/lcci-0107-rotate-matrix' },
                { text: '面试题 01.08. 零矩阵', link: '/lcci/lcci-0108-zero-matrix' },
                { text: '面试题 01.09. 字符串轮转', link: '/lcci/lcci-0109-string-rotation' },
                { text: '面试题 02.01. 移除重复节点', link: '/lcci/lcci-0201-remove-duplicate-node' },
                { text: '面试题 02.02. 返回倒数第 k 个节点', link: '/lcci/lcci-0202-kth-node-from-end-of-list' },
                { text: '面试题 02.03. 删除中间节点', link: '/lcci/lcci-0203-delete-middle-node' },
                { text: '面试题 02.04. 分割链表', link: '/lcci/lcci-0204-partition-list' },
                { text: '面试题 02.05. 链表求和', link: '/lcci/lcci-0205-sum-lists' },
                { text: '面试题 02.06. 回文链表', link: '/lcci/lcci-0206-palindrome-linked-list' },
                { text: '面试题 02.07. 链表相交', link: '/lcci/lcci-0207-intersection-of-two-linked-lists' },
                { text: '面试题 02.08. 环路检测', link: '/lcci/lcci-0208-linked-list-cycle' },
                { text: '面试题 03.01. 三合一', link: '/lcci/lcci-0301-three-in-one' },
                { text: '面试题 03.02. 栈的最小值', link: '/lcci/lcci-0302-min-stack' },
                { text: '面试题 03.03. 堆盘子', link: '/lcci/lcci-0303-stack-of-plates' },
                { text: '面试题 03.04. 化栈为队', link: '/lcci/lcci-0304-implement-queue-using-stacks' },
                { text: '面试题 03.05. 栈排序', link: '/lcci/lcci-0305-sort-of-stacks' },
                { text: '面试题 03.06. 动物收容所', link: '/lcci/lcci-0306-animal-shelter' },
                { text: '面试题 04.01. 节点间通路', link: '/lcci/lcci-0401-route-between-nodes' },
                { text: '面试题 04.02. 最小高度树', link: '/lcci/lcci-0402-minimum-height-tree' },
                { text: '面试题 04.03. 特定深度节点链表', link: '/lcci/lcci-0403-list-of-depth' },
                { text: '面试题 04.04. 检查平衡性', link: '/lcci/lcci-0404-check-balance' },
                { text: '面试题 04.05. 合法二叉搜索树', link: '/lcci/lcci-0405-legal-binary-search-tree' },
                { text: '面试题 04.06. 后继者', link: '/lcci/lcci-0406-successor' },
                { text: '面试题 04.08. 首个共同祖先', link: '/lcci/lcci-0408-first-common-ancestor' },
                { text: '面试题 04.09. 二叉搜索树序列', link: '/lcci/lcci-0409-bst-sequences' },
                { text: '面试题 04.10. 检查子树', link: '/lcci/lcci-0410-check-subtree' },
                { text: '面试题 04.12. 求和路径', link: '/lcci/lcci-0412-paths-with-sum' },
                { text: '面试题 05.01. 插入', link: '/lcci/lcci-0501-insert-into-bits' },
                { text: '面试题 05.02. 二进制数转字符串', link: '/lcci/lcci-0502-binary-number-to-string' },
                { text: '面试题 05.03. 翻转数位', link: '/lcci/lcci-0503-reverse-bits' },
                { text: '面试题 05.04. 下一个数', link: '/lcci/lcci-0504-closed-number' },
                { text: '面试题 05.06. 整数转换', link: '/lcci/lcci-0506-convert-integer' },
                { text: '面试题 05.07. 配对交换', link: '/lcci/lcci-0507-exchange' },
                { text: '面试题 05.08. 绘制直线', link: '/lcci/lcci-0508-draw-line' },
                { text: '面试题 08.01. 三步问题', link: '/lcci/lcci-0801-three-steps-problem' },
                { text: '面试题 08.02. 迷路的机器人', link: '/lcci/lcci-0802-robot-in-a-grid' },
                { text: '面试题 08.03. 魔术索引', link: '/lcci/lcci-0803-magic-index' },
                { text: '面试题 08.04. 幂集', link: '/lcci/lcci-0804-power-set' },
                { text: '面试题 08.05. 递归乘法', link: '/lcci/lcci-0805-recursive-mulitply' },
                { text: '面试题 16.11. 跳水板', link: '/lcci/lcci-1611-diving-board' },
                { text: '面试题 16.13. 平分正方形', link: '/lcci/lcci-1613-bisect-squares' },
                { text: '面试题 16.14. 最佳直线', link: '/lcci/lcci-1614-best-line' },
                { text: '面试题 16.15. 珠玑妙算', link: '/lcci/lcci-1615-master-mind' },
                { text: '面试题 16.16. 部分排序', link: '/lcci/lcci-1616-sub-sort' },
                { text: '面试题 16.17. 连续数列', link: '/lcci/lcci-1617-contiguous-sequence' },
                { text: '面试题 16.18. 模式匹配', link: '/lcci/lcci-1618-pattern-matching' },
                { text: '面试题 16.19. 水域大小', link: '/lcci/lcci-1619-pond-sizes' }
            ]
        }
    ],
}
