import type { DefaultTheme } from 'vitepress'

export const sidebar: DefaultTheme.Config['sidebar'] = {

    '/': [
        { text: 'LeetCode', link: '/leetcode/1-two-sum' }
    ],
    '/leetcode/': [
        { text: '1. 两数之和', link: '/leetcode/1-two-sum' },
        { text: '2. 两数相加', link: '/leetcode/2-add-two-numbers' },
        { text: '3. 无重复字符的最长子串', link: '/leetcode/3-longest-substring-without-repeating-characters' },
        { text: '4. 寻找两个正序数组的中位数', link: '/leetcode/4-median-of-two-sorted-arrays' },
        { text: '5. 最长回文子串', link: '/leetcode/5-longest-palindromic-substring' },
        { text: '6. Z 字形变换', link: '/leetcode/6-zigzag-conversion' },
        { text: '7. 整数反转', link: '/leetcode/7-reverse-integer' },
        { text: '8. 字符串转换整数 (atoi)', link: '/leetcode/8-string-to-integer-atoi' },
        { text: '9. 回文数', link: '/leetcode/9-palindrome-number' },
        { text: '10. 正则表达式匹配', link: '/leetcode/10-regular-expression-matching' },
        { text: '11. 盛最多水的容器', link: '/leetcode/11-container-with-most-water' },
        { text: '12. 整数转罗马数字', link: '/leetcode/12-integer-to-roman' },
        { text: '13. 罗马数字转整数', link: '/leetcode/13-roman-to-integer' },
        { text: '14. 最长公共前缀', link: '/leetcode/14-longest-common-prefix' },
        { text: '15. 三数之和', link: '/leetcode/15-3sum' },
        { text: '16. 最接近的三数之和', link: '/leetcode/16-3sum-closest' },
        { text: '17. 电话号码的字母组合', link: '/leetcode/17-letter-combinations-of-a-phone-number' },
        { text: '18. 四数之和', link: '/leetcode/18-4sum' },
        { text: '19. 删除链表的倒数第 N 个结点', link: '/leetcode/19-remove-nth-node-from-end-of-list' },
        { text: '20. 有效的括号', link: '/leetcode/20-valid-parentheses' },
        { text: '21. 合并两个有序链表', link: '/leetcode/21-merge-two-sorted-lists' },
        { text: '22. 括号生成', link: '/leetcode/22-generate-parentheses' },
        { text: '23. 合并 K 个升序链表', link: '/leetcode/23-merge-k-sorted-lists' },
        { text: '24. 两两交换链表中的节点', link: '/leetcode/24-swap-nodes-in-pairs' },
        { text: '25. K 个一组翻转链表', link: '/leetcode/25-reverse-nodes-in-k-group' },
        { text: '26. 删除有序数组中的重复项', link: '/leetcode/26-remove-duplicates-from-sorted-array' },
        { text: '27. 移除元素', link: '/leetcode/27-remove-element' },
        { text: '28. 找出字符串中第一个匹配项的下标', link: '/leetcode/28-find-the-index-of-the-first-occurrence-in-a-string' },
        { text: '29. 两数相除', link: '/leetcode/29-divide-two-integers' },
        { text: '30. 串联所有单词的子串', link: '/leetcode/30-substring-with-concatenation-of-all-words' },
        { text: '31. 下一个排列', link: '/leetcode/31-next-permutation' },
        { text: '32. 最长有效括号', link: '/leetcode/32-longest-valid-parentheses' },
        { text: '33. 搜索旋转排序数组', link: '/leetcode/33-search-in-rotated-sorted-array' },
        { text: '34. 在排序数组中查找元素的第一个和最后一个位置', link: '/leetcode/34-find-first-and-last-position-of-element-in-sorted-array' },
        { text: '35. 搜索插入位置', link: '/leetcode/35-search-insert-position' },
        { text: '36. 有效的数独', link: '/leetcode/36-valid-sudoku' },
        { text: '37. 解数独', link: '/leetcode/37-sudoku-solver' },
        { text: '38. 外观数列', link: '/leetcode/38-count-and-say' },
        { text: '39. 组合总和', link: '/leetcode/39-combination-sum' },
        { text: '40. 组合总和 II', link: '/leetcode/40-combination-sum-ii' },
        { text: '41. 缺失的第一个正数', link: '/leetcode/41-first-missing-positive' },
        { text: '42. 接雨水', link: '/leetcode/42-trapping-rain-water' },
        { text: '43. 字符串相乘', link: '/leetcode/43-multiply-strings' },
        { text: '44. 通配符匹配', link: '/leetcode/44-wildcard-matching' },
        { text: '45. 跳跃游戏 II', link: '/leetcode/45-jump-game-ii' },
        { text: '46. 全排列', link: '/leetcode/46-permutations' },
        { text: '47. 全排列 II', link: '/leetcode/47-permutations-ii' },
        { text: '48. 旋转图像', link: '/leetcode/48-rotate-image' },
        { text: '49. 字母异位词分组', link: '/leetcode/49-group-anagrams' },
        { text: '50. Pow(x, n)', link: '/leetcode/50-powx-n' },
        { text: '51. N 皇后', link: '/leetcode/51-n-queens' },
        { text: '52. N 皇后 II', link: '/leetcode/52-n-queens-ii' },
        { text: '53. 最大子数组和', link: '/leetcode/53-maximum-subarray' },
        { text: '54. 螺旋矩阵', link: '/leetcode/54-spiral-matrix' },
        { text: '55. 跳跃游戏', link: '/leetcode/55-jump-game' },
        { text: '56. 合并区间', link: '/leetcode/56-merge-intervals' },
        { text: '57. 插入区间', link: '/leetcode/57-insert-interval' },
        { text: '58. 最后一个单词的长度', link: '/leetcode/58-length-of-last-word' },
        { text: '59. 螺旋矩阵 II', link: '/leetcode/59-spiral-matrix-ii' },
        { text: '60. 排列序列', link: '/leetcode/60-permutation-sequence' },
        { text: '61. 旋转链表', link: '/leetcode/61-rotate-list' },
        { text: '62. 不同路径', link: '/leetcode/62-unique-paths' },
        { text: '63. 不同路径 II', link: '/leetcode/63-unique-paths-ii' },
        { text: '64. 最小路径和', link: '/leetcode/64-minimum-path-sum' },
        { text: '65. 有效数字', link: '/leetcode/65-valid-number' },
        { text: '66. 加一', link: '/leetcode/66-plus-one' },
        { text: '67. 二进制求和', link: '/leetcode/67-add-binary' },
        { text: '68. 文本左右对齐', link: '/leetcode/68-text-justification' },
        { text: '69. x 的平方根', link: '/leetcode/69-sqrtx' },
        { text: '70. 爬楼梯', link: '/leetcode/70-climbing-stairs' },
        { text: '71. 简化路径', link: '/leetcode/71-simplify-path' },
        { text: '72. 编辑距离', link: '/leetcode/72-edit-distance' },
        { text: '73. 矩阵置零', link: '/leetcode/73-set-matrix-zeroes' },
        { text: '74. 搜索二维矩阵', link: '/leetcode/74-search-a-2d-matrix' },
        { text: '75. 颜色分类', link: '/leetcode/75-sort-colors' },
        { text: '76. 最小覆盖子串', link: '/leetcode/76-minimum-window-substring' },
        { text: '77. 组合', link: '/leetcode/77-combinations' },
        { text: '78. 子集', link: '/leetcode/78-subsets' },
        { text: '79. 单词搜索', link: '/leetcode/79-word-search' },
        { text: '80. 删除有序数组中的重复项 II', link: '/leetcode/80-remove-duplicates-from-sorted-array-ii' },
        { text: '81. 搜索旋转排序数组 II', link: '/leetcode/81-search-in-rotated-sorted-array-ii' },
        { text: '82. 删除排序链表中的重复元素 II', link: '/leetcode/82-remove-duplicates-from-sorted-list-ii' },
        { text: '83. 删除排序链表中的重复元素', link: '/leetcode/83-remove-duplicates-from-sorted-list' },
        { text: '84. 柱状图中最大的矩形', link: '/leetcode/84-largest-rectangle-in-histogram' },
        { text: '85. 最大矩形', link: '/leetcode/85-maximal-rectangle' },
        { text: '86. 分隔链表', link: '/leetcode/86-partition-list' },
        { text: '87. 扰乱字符串', link: '/leetcode/87-scramble-string' },
        { text: '88. 合并两个有序数组', link: '/leetcode/88-merge-sorted-array' },
        { text: '89. 格雷编码', link: '/leetcode/89-gray-code' },
        { text: '90. 子集 II', link: '/leetcode/90-subsets-ii' },
        { text: '91. 解码方法', link: '/leetcode/91-decode-ways' },
        { text: '92. 反转链表 II', link: '/leetcode/92-reverse-linked-list-ii' },
        { text: '93. 复原 IP 地址', link: '/leetcode/93-restore-ip-addresses' },
        { text: '94. 二叉树的中序遍历', link: '/leetcode/94-binary-tree-inorder-traversal' },
        { text: '95. 不同的二叉搜索树 II', link: '/leetcode/95-unique-binary-search-trees-ii' },
        { text: '96. 不同的二叉搜索树', link: '/leetcode/96-unique-binary-search-trees' },
        { text: '97. 交错字符串', link: '/leetcode/97-interleaving-string' },
        { text: '98. 验证二叉搜索树', link: '/leetcode/98-validate-binary-search-tree' },
        { text: '99. 恢复二叉搜索树', link: '/leetcode/99-recover-binary-search-tree' },
        { text: '100. 相同的树', link: '/leetcode/100-same-tree' }
    ],
}
